/** Level 1 auth copy — trust-safe, non-leaky error messages */

export const AUTH_COPY = {
  identityWelcomeTitle: 'Welcome to Skeldir',
  identityWelcomeSubtitle: 'Sign in to your account or create a new one',
  loginTitle: 'Welcome to Skeldir',
  signupTitle: 'Create your account',
  loginSubtitle: 'Resume your product session to supervise verified revenue trust.',
  signupSubtitle: 'Create the identity required before organization setup.',
  identityInviteFraming: (organizationName: string) =>
    `You've been invited to join ${organizationName}. Sign in or create an account to continue.`,
  emailLabel: 'Email',
  passwordLabel: 'Password',
  confirmPasswordLabel: 'Confirm password',
  firstNameLabel: 'First name',
  lastNameLabel: 'Last name',
  workspaceLabel: 'Workspace name',
  organizationNameLabel: 'Organization name',
  inviteTeammatesLabel: 'Invite teammates',
  inviteTeammatesHint: 'Optional — enter email addresses separated by commas.',
  submitLogin: 'Sign In',
  submitSignup: 'Sign Up',
  submitCreateOrganization: 'Create Organization',
  submitting: 'Submitting…',
  oauthDivider: 'or',
  toggleToSignup: "Don't have an account? Sign Up",
  toggleToSignin: 'Already have an account? Sign In',
  continueWithGoogle: 'Continue with Google',
  createOrganizationTitle: 'Create Your Organization',
  joinExistingOrganization: 'Join an existing organization',
  notAMemberTitle: 'You are not a member of an organization',
  notAMemberBody: 'Ask your organization admin to send you an invite link.',
  notAMemberCreateOrg: 'Create a new organization',
  notAMemberCheckEmail: 'Check your email for an invite',
  sessionExpired: 'Your session expired. Sign in again to resume product access.',
  invalidCredentials: 'Email or password is incorrect.',
  networkFailure: 'Unable to reach Skeldir auth services. No session was created.',
  rateLimited: 'Too many attempts. Wait before trying again.',
  permissionDenied: 'You do not have permission to access this workspace.',
  emailNotBusiness: 'Use a business email address for workspace creation.',
  passwordMismatch: 'Passwords must match.',
  confirmPasswordRequired: 'Confirm your password.',
  firstNameRequired: 'Enter your first name.',
  lastNameRequired: 'Enter your last name.',
  organizationNameRequired: 'Enter an organization name.',
  tenantAlreadyExists: 'A workspace already exists for this email.',
  tenantCreationPending: 'Workspace creation is in progress.',
  tenantCreationFailed: 'Workspace creation failed. No tenant state was created.',
  oauthUnavailable: (provider: string) => `${provider} sign-in is temporarily unavailable.`,
  oauthCallbackError: (provider: string) => `${provider} sign-in could not be completed.`,
  oauthPending: (provider: string) => `Connecting to ${provider}…`,
  unsafeRedirect: 'That redirect target is not permitted.',
  alreadyAuthenticated: 'You are already signed in.',
  handoffSessionTitle: 'Session established',
  handoffSessionBody:
    'Your product session is active. Continue into the app frame when your workspace is ready.',
  handoffWorkspaceTitle: 'Workspace created',
  handoffWorkspaceBody:
    'Your workspace exists. Enter the app frame to begin supervised trust workflows once downstream levels unlock.',
  enterAppFrame: 'Enter app frame',
  continueToLogin: 'Return to sign in',
  createAccount: 'Create a workspace',
  haveAccount: 'Already have a workspace?',
  unknownAuthState: 'Unknown auth state. Sign in again or contact support.',
  supportFooterPrefix: "We're here to help at",
  supportEmail: 'sales@skeldir.com',
} as const;
