openapi: 3.1.0
info:
  title: Skeldir WooCommerce Webhook API
  version: 1.0.0
  description: WooCommerce webhook ingestion endpoints for Skeldir Attribution Intelligence platform
servers:
  - url: https://api.skeldir.com
    description: Production server
  - url: http://localhost:4016
    description: Prism mock server for frontend development
paths:
  /webhooks/woocommerce/order/created:
    post:
      operationId: woocommerceOrderCreated
      tags:
        - Webhooks
        - WooCommerce
      summary: WooCommerce order creation webhook
      description: |
        Receives WooCommerce order creation webhooks for revenue attribution.
        
        **Security**: This endpoint validates HMAC-SHA256 signatures using the X-WC-Webhook-Signature header.
        The webhook secret must be configured in the tenant settings.
        
        **Privacy**: All PII (emails, names, addresses, phone numbers) is stripped from the payload before persistence.
        No storage of personally identifiable information occurs. Only session-scoped data is retained for attribution purposes.
        Session IDs are ephemeral (30-minute inactivity timeout) and are NOT used for cross-session tracking.
      security: []
      parameters:
        - name: X-WC-Webhook-Signature
          in: header
          required: true
          schema:
            type: string
          description: HMAC-SHA256 signature for webhook verification
        - name: X-WC-Webhook-Source
          in: header
          required: true
          schema:
            type: string
          description: WooCommerce webhook source URL
        - name: X-Correlation-ID
          in: header
          required: false
          schema:
            type: string
            format: uuid
          description: Distributed tracing correlation ID (generated if not provided)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: |
                WooCommerce order webhook payload. Note: PII fields (billing_email, billing_address, shipping_address, customer details)
                are stripped before persistence. Only order ID, total, currency, and date_created are retained.
              properties:
                id:
                  type: integer
                  description: WooCommerce order ID (used for idempotency)
                total:
                  type: string
                  description: Order total as string (will be converted to cents)
                currency:
                  type: string
                  description: Order currency code
                date_created:
                  type: string
                  format: date-time
                  description: Order creation timestamp
      responses:
        '200':
          description: Webhook processed successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - acknowledged
                  - event_id
                properties:
                  acknowledged:
                    type: boolean
                    example: true
                  event_id:
                    type: string
                    description: Internal event ID for tracking
                    example: "evt_550e8400e29b41d4a716446655440000"
              examples:
                success:
                  summary: Webhook acknowledged
                  value:
                    acknowledged: true
                    event_id: "evt_550e8400e29b41d4a716446655440000"
        '400':
          description: Invalid webhook payload or signature
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '../../_common/v1/components.yaml#/components/schemas/Problem'
              examples:
                invalid_signature:
                  summary: Invalid HMAC signature
                  value:
                    type: "https://api.skeldir.com/problems/invalid-webhook-signature"
                    title: "Invalid Webhook Signature"
                    status: 400
                    detail: "HMAC signature validation failed"
                    instance: "/webhooks/woocommerce/order/created"
                    error_id: "550e8400-e29b-41d4-a716-446655440000"
                    correlation_id: "550e8400-e29b-41d4-a716-446655440000"
        '401':
          $ref: '../../_common/v1/components.yaml#/components/responses/Unauthorized'
components: {}
