export const OPERATIONAL_AUDIT_COPY = {
  diagnosticsPageTitle: 'Operational diagnostics',
  diagnosticsPageDescription:
    'Inspect operational queue state, task failures, and integration degradation. Diagnostics explain infrastructure status — they do not create or validate financial truth.',
  auditPageTitle: 'Audit Ledger',
  auditPageDescription:
    'Search audit events and inspect supporting artifacts. Audit events enable reconstruction — they are not revenue claims.',
  auditFiltersLabel: 'Audit filters',
  forensicFiltersLabel: 'Audit Filters',
  filterDateRange: 'Date range',
  filterDateStart: 'Start',
  filterDateEnd: 'End',
  filterWhoDidIt: 'Who did it',
  filterWhoPlaceholder: 'Sarah Chen or Budget Optimizer',
  filterWhatTheyDid: 'What they did',
  filterWhatTheyDidAll: 'All actions',
  filterOrderClaim: 'Which order / claim',
  filterOrderClaimPlaceholder: 'ORD-8821',
  filterEnvelope: 'Which envelope',
  filterEnvelopePlaceholder: 'env_te_9f2a8b1c',
  auditApplyFilters: 'Apply',
  auditClearFilters: 'Clear',
  auditTableCaption: 'Tenant audit events',
  dlqTableCaption: 'Operational queue events',
  openArtifactAction: 'Open artifact',
  artifactDrawerTitle: 'Audit artifact',
  artifactUnavailableTitle: 'Artifact unavailable',
  artifactCorruptedTitle: 'Artifact corrupted',
  artifactAccessDeniedTitle: 'Artifact access denied',
  artifactInvalidSignature: 'Invalid signature status returned.',
  jsonPreviewLabel: 'Redacted JSON preview',
  jsonPreviewHidden: 'Raw payload hidden by default for privacy safety.',
  repairContextTitle: 'Repair context',
  repairContextBody:
    'Review integration status and retry guidance. Level 5 does not execute repairs or mutate backend state.',
  permissionDeniedAudit: 'You do not have permission to view the audit ledger.',
  permissionDeniedDiagnostics: 'You do not have permission to view operational diagnostics.',
  permissionDeniedArtifact: 'You do not have permission to open audit artifacts.',
  healthOperational: 'Trust systems operational',
  healthConfidenceDegraded: 'Confidence degraded',
  healthApiPaused: 'Trust API paused',
  healthIntegrationAttention: 'Integration attention needed',
  healthUnknown: 'Unknown system health state',
  healthLoading: 'Loading system health…',
  healthFetchFailed: 'System health unavailable',
  healthTooltipOperational:
    'Operational dependencies are available. Deterministic truth may remain readable while confidence compute is delayed.',
  healthTooltipConfidenceDegraded:
    'Probabilistic confidence may be delayed or unavailable. Deterministic verification remains active.',
  healthTooltipApiPaused: 'External trust reads are paused by an audited control-plane switch.',
  healthTooltipIntegrationAttention:
    'Commerce or claim integrations need repair. This reflects connection state, not claim correctness.',
  healthTooltipUnknown: 'Health state could not be classified. Fail closed until resolved.',
  healthClickLabel: 'View system health audit events',
  diagnosticEmpty: 'No operational issues in the current window.',
  auditEmpty: 'No audit events recorded for this tenant yet.',
  auditFilteredEmpty: 'No audit events match these filters.',
  forensicEventNotFoundTitle: 'Forensic record unavailable',
  forensicEventNotFoundReason: (eventId: string) =>
    `Audit reference ${eventId} could not be resolved for this tenant.`,
  forensicEventNotFoundBoundary:
    'The missing record does not alter the TrustEnvelope or its deterministic financial truth.',
  returnToForensicLedger: 'Return to Forensic Log',
  forensicEventLoadFailed: 'Forensic record could not be loaded.',
  retryForensicEvent: 'Retry',
  auditLogModeLabel: 'Audit log view',
  auditLogModeAccess: 'Access History',
  auditLogModeAccessDescription: 'Who viewed TrustEnvelopes and API endpoints.',
  auditLogModeForensic: 'Forensic Log',
  auditLogModeForensicDescription:
    'Who exported, approved, or dispatched consequence-bearing actions.',
  auditSortLockedNote: 'Timeline locked to newest-first for chain-of-custody.',
  viewTechnicalDetails: 'View Technical Details',
  forensicBusinessDetail: {
    breadcrumbLedger: 'Audit Ledger',
    exportedSummary:
      'A signed export artifact was generated for this trust envelope. Review the export destination and verify the signature before sharing externally.',
    policyDecisionSummary:
      'A policy decision was recorded for this tenant. Review the governing rule and whether approval is still required before any external action executes.',
    proposalSummary:
      'A budget proposal was generated from verified revenue and policy constraints. Review the recommended allocation before submitting for certification.',
    exceptionSummary:
      'An exception case was updated. Review the business impact and choose whether to resolve, dispute, or request more evidence.',
    defaultSummary:
      'This consequence-bearing audit event is available for supervisory review. Open technical details only if you need cryptographic proof.',
    signatureVerificationAction: 'Verify signature',
    reviewPolicyAction: 'Review policy authority',
    submitProposalAction: 'Submit for certification',
    resolveExceptionAction: 'Mark resolved',
  },
  forensicTechnicalDrawerTitle: 'Technical audit details',
  forensicIdempotencyTitle: 'Idempotency',
  forensicIdempotencyBody:
    'This key ensures the system processes this action only once, even if retries occur.',
  forensicSemanticTruthTitle: 'Explanation provenance',
  forensicInputStateTitle: 'Input state',
  forensicMetadataTitle: 'Technical metadata',
  auditLoadMore: 'Load more',
  auditLoadingMore: 'Loading more events…',
  auditLoadedCountLabel: 'events loaded',
  chainIntactBadge: 'Chain Intact',
  chainIntactDetail: 'This log is legally tamper-proof.',
  chainBrokenBadge: 'Chain Broken: Tamper or Gap Detected',
  chainBrokenDetail: 'Someone may have altered or deleted a record in the middle.',
  chainUnavailableBadge: 'Chain verification unavailable',
  forensicDrawerTitle: 'Forensic inspector',
  forensicDrawerReadOnly: 'Read-only evidence view. No edits are permitted.',
  hashChainSectionTitle: 'Hash chain',
  auditTableCaptionAccess: 'Access history events',
  auditTableCaptionForensic: 'Forensic log events',
  auditTableSectionTitleAccess: 'Access history',
  auditTableSectionTitleForensic: 'Forensic log',
  summaryTaskFailures: 'Task failures',
  summaryIntegrationIssues: 'Integration issues',
  summaryConfidenceDelayed: 'Confidence delayed',
  summaryTrustApiPaused: 'Trust API paused',
  artifactHashPlaceholder: 'artifact_hash_placeholder',
  redactedArtifactPayload: 'redacted_artifact_payload',
} as const;

export const HEALTH_STATE_LABELS = {
  operational: OPERATIONAL_AUDIT_COPY.healthOperational,
  confidence_degraded: OPERATIONAL_AUDIT_COPY.healthConfidenceDegraded,
  api_paused: OPERATIONAL_AUDIT_COPY.healthApiPaused,
  integration_attention: OPERATIONAL_AUDIT_COPY.healthIntegrationAttention,
  unknown: OPERATIONAL_AUDIT_COPY.healthUnknown,
  loading: OPERATIONAL_AUDIT_COPY.healthLoading,
  fetch_failed: OPERATIONAL_AUDIT_COPY.healthFetchFailed,
} as const;
