openapi: 3.1.0
info:
  title: Skeldir Reconciliation API
  version: 2.0.0
  description: Platform reconciliation status endpoints

servers:
  - url: http://localhost:4013
    description: Mock server

paths:
  /api/reconciliation/status:
    get:
      summary: Get reconciliation status for all platforms
      operationId: getReconciliationStatus
      parameters:
        - $ref: './base.yaml#/components/parameters/CorrelationId'
        - $ref: './base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Reconciliation status
          content:
            application/json:
              schema:
                type: object
                required:
                  - platforms
                properties:
                  platforms:
                    type: array
                    items:
                      type: object
                      required:
                        - platform_name
                        - connection_status
                        - last_sync
                      properties:
                        platform_name:
                          type: string
                          enum: [Meta, Google, TikTok, LinkedIn, Shopify, WooCommerce, Stripe, PayPal]
                        connection_status:
                          type: string
                          enum: [verified, partial, pending, failed]
                        last_sync:
                          type: string
                          format: date-time
                        error_message:
                          type: string
        '401':
          $ref: './base.yaml#/components/responses/UnauthorizedError'
