/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user with email and password, returns JWT tokens
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchange a valid refresh token for a new access token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Invalidate current session and tokens
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify token validity
         * @description Check if the current access token is valid
         */
        get: operations["verifyToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC7807 Problem Details for HTTP APIs with Skeldir extensions */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type
             * @example https://api.skeldir.com/problems/authentication-failed
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem
             * @example Authentication Failed
             */
            title: string;
            /**
             * @description HTTP status code
             * @example 401
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence
             * @example The provided JWT token has expired. Please refresh your authentication token.
             */
            detail: string;
            /**
             * Format: uri
             * @description URI reference identifying this specific occurrence
             * @example https://api.skeldir.com/api/attribution/revenue/realtime
             */
            instance: string;
            /**
             * Format: uuid
             * @description Request correlation ID for distributed tracing
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            correlation_id: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the error occurred
             * @example 2025-11-11T14:32:00Z
             */
            timestamp: string;
            /** @description Optional array of specific validation errors */
            errors?: {
                /** @example email */
                field?: string;
                /** @example Invalid email format */
                message?: string;
                /** @example INVALID_FORMAT */
                code?: string;
            }[];
        };
        SuccessResponse: {
            success: boolean;
            /** Format: uuid */
            correlation_id: string;
            message?: string;
        };
    };
    responses: {
        /** @description Unauthorized - invalid or missing authentication */
        UnauthorizedError: {
            headers: {
                /** @description Request correlation ID for distributed tracing */
                "X-Correlation-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type
                     * @example https://api.skeldir.com/problems/authentication-failed
                     */
                    type: string;
                    /**
                     * @description Short, human-readable summary of the problem
                     * @example Authentication Failed
                     */
                    title: string;
                    /**
                     * @description HTTP status code
                     * @example 401
                     */
                    status: number;
                    /**
                     * @description Human-readable explanation specific to this occurrence
                     * @example The provided JWT token has expired. Please refresh your authentication token.
                     */
                    detail: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this specific occurrence
                     * @example https://api.skeldir.com/api/attribution/revenue/realtime
                     */
                    instance: string;
                    /**
                     * Format: uuid
                     * @description Request correlation ID for distributed tracing
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    correlation_id: string;
                    /**
                     * Format: date-time
                     * @description ISO 8601 timestamp when the error occurred
                     * @example 2025-11-11T14:32:00Z
                     */
                    timestamp: string;
                    /** @description Optional array of specific validation errors */
                    errors?: {
                        /** @example email */
                        field?: string;
                        /** @example Invalid email format */
                        message?: string;
                        /** @example INVALID_FORMAT */
                        code?: string;
                    }[];
                };
            };
        };
        /** @description Forbidden - authenticated but insufficient permissions */
        ForbiddenError: {
            headers: {
                "X-Correlation-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type
                     * @example https://api.skeldir.com/problems/authentication-failed
                     */
                    type: string;
                    /**
                     * @description Short, human-readable summary of the problem
                     * @example Authentication Failed
                     */
                    title: string;
                    /**
                     * @description HTTP status code
                     * @example 401
                     */
                    status: number;
                    /**
                     * @description Human-readable explanation specific to this occurrence
                     * @example The provided JWT token has expired. Please refresh your authentication token.
                     */
                    detail: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this specific occurrence
                     * @example https://api.skeldir.com/api/attribution/revenue/realtime
                     */
                    instance: string;
                    /**
                     * Format: uuid
                     * @description Request correlation ID for distributed tracing
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    correlation_id: string;
                    /**
                     * Format: date-time
                     * @description ISO 8601 timestamp when the error occurred
                     * @example 2025-11-11T14:32:00Z
                     */
                    timestamp: string;
                    /** @description Optional array of specific validation errors */
                    errors?: {
                        /** @example email */
                        field?: string;
                        /** @example Invalid email format */
                        message?: string;
                        /** @example INVALID_FORMAT */
                        code?: string;
                    }[];
                };
            };
        };
        /** @description Too Many Requests - rate limit exceeded */
        RateLimitError: {
            headers: {
                "X-Correlation-ID"?: string;
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type
                     * @example https://api.skeldir.com/problems/authentication-failed
                     */
                    type: string;
                    /**
                     * @description Short, human-readable summary of the problem
                     * @example Authentication Failed
                     */
                    title: string;
                    /**
                     * @description HTTP status code
                     * @example 401
                     */
                    status: number;
                    /**
                     * @description Human-readable explanation specific to this occurrence
                     * @example The provided JWT token has expired. Please refresh your authentication token.
                     */
                    detail: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this specific occurrence
                     * @example https://api.skeldir.com/api/attribution/revenue/realtime
                     */
                    instance: string;
                    /**
                     * Format: uuid
                     * @description Request correlation ID for distributed tracing
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    correlation_id: string;
                    /**
                     * Format: date-time
                     * @description ISO 8601 timestamp when the error occurred
                     * @example 2025-11-11T14:32:00Z
                     */
                    timestamp: string;
                    /** @description Optional array of specific validation errors */
                    errors?: {
                        /** @example email */
                        field?: string;
                        /** @example Invalid email format */
                        message?: string;
                        /** @example INVALID_FORMAT */
                        code?: string;
                    }[];
                };
            };
        };
    };
    parameters: {
        /** @description Unique request correlation ID for distributed tracing */
        CorrelationId: string;
        /** @description Bearer token for authentication (format - Bearer <token>) */
        Authorization: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request correlation ID for distributed tracing */
                "X-Correlation-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "user@example.com",
                 *       "password": "securepassword123"
                 *     }
                 */
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "expires_in": 3600,
                     *       "user": {
                     *         "id": "550e8400-e29b-41d4-a716-446655440000",
                     *         "email": "user@example.com",
                     *         "username": "testuser"
                     *       }
                     *     }
                     */
                    "application/json": {
                        /** @description JWT access token */
                        access_token: string;
                        /** @description JWT refresh token for obtaining new access tokens */
                        refresh_token: string;
                        /**
                         * @description Token expiration time in seconds
                         * @example 3600
                         */
                        expires_in: number;
                        user: {
                            /** Format: uuid */
                            id?: string;
                            /** Format: email */
                            email?: string;
                            username?: string;
                        };
                    };
                };
            };
            /** @description Unauthorized - invalid or missing authentication */
            401: {
                headers: {
                    /** @description Request correlation ID for distributed tracing */
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
            /** @description Forbidden - authenticated but insufficient permissions */
            403: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
            /** @description Too Many Requests - rate limit exceeded */
            429: {
                headers: {
                    "X-Correlation-ID"?: string;
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request correlation ID for distributed tracing */
                "X-Correlation-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The refresh token from login response */
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "expires_in": 3600
                     *     }
                     */
                    "application/json": {
                        /** @description New JWT access token */
                        access_token: string;
                        /** @description New refresh token (token rotation) */
                        refresh_token?: string;
                        /** @description Token expiration time in seconds */
                        expires_in: number;
                    };
                };
            };
            /** @description Unauthorized - invalid or missing authentication */
            401: {
                headers: {
                    /** @description Request correlation ID for distributed tracing */
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
            /** @description Forbidden - authenticated but insufficient permissions */
            403: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request correlation ID for distributed tracing */
                "X-Correlation-ID": string;
                /** @description Bearer token for authentication (format - Bearer <token>) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "correlation_id": "00000000-0000-0000-0000-000000000000",
                     *       "message": "Session terminated"
                     *     }
                     */
                    "application/json": {
                        success: boolean;
                        /** Format: uuid */
                        correlation_id: string;
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized - invalid or missing authentication */
            401: {
                headers: {
                    /** @description Request correlation ID for distributed tracing */
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
            /** @description Forbidden - authenticated but insufficient permissions */
            403: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request correlation ID for distributed tracing */
                "X-Correlation-ID": string;
                /** @description Bearer token for authentication (format - Bearer <token>) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "valid": true,
                     *       "user_id": "550e8400-e29b-41d4-a716-446655440000",
                     *       "expires_at": "2025-11-26T15:30:00Z"
                     *     }
                     */
                    "application/json": {
                        /** @example true */
                        valid: boolean;
                        /** Format: uuid */
                        user_id: string;
                        /** Format: date-time */
                        expires_at?: string;
                    };
                };
            };
            /** @description Unauthorized - invalid or missing authentication */
            401: {
                headers: {
                    /** @description Request correlation ID for distributed tracing */
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
            /** @description Forbidden - authenticated but insufficient permissions */
            403: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type
                         * @example https://api.skeldir.com/problems/authentication-failed
                         */
                        type: string;
                        /**
                         * @description Short, human-readable summary of the problem
                         * @example Authentication Failed
                         */
                        title: string;
                        /**
                         * @description HTTP status code
                         * @example 401
                         */
                        status: number;
                        /**
                         * @description Human-readable explanation specific to this occurrence
                         * @example The provided JWT token has expired. Please refresh your authentication token.
                         */
                        detail: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this specific occurrence
                         * @example https://api.skeldir.com/api/attribution/revenue/realtime
                         */
                        instance: string;
                        /**
                         * Format: uuid
                         * @description Request correlation ID for distributed tracing
                         * @example 550e8400-e29b-41d4-a716-446655440000
                         */
                        correlation_id: string;
                        /**
                         * Format: date-time
                         * @description ISO 8601 timestamp when the error occurred
                         * @example 2025-11-11T14:32:00Z
                         */
                        timestamp: string;
                        /** @description Optional array of specific validation errors */
                        errors?: {
                            /** @example email */
                            field?: string;
                            /** @example Invalid email format */
                            message?: string;
                            /** @example INVALID_FORMAT */
                            code?: string;
                        }[];
                    };
                };
            };
        };
    };
}
