/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system health status */
        get: operations["getHealthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type
             * @example https://api.skeldir.com/problems/authentication-failed
             */
            type: string;
            /**
             * @description Short, human-readable summary of the problem
             * @example Authentication Failed
             */
            title: string;
            /**
             * @description HTTP status code
             * @example 401
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence
             * @example The provided JWT token has expired. Please refresh your authentication token.
             */
            detail: string;
            /**
             * Format: uri
             * @description URI reference identifying this specific occurrence
             * @example /api/attribution/revenue/realtime
             */
            instance: string;
            /**
             * Format: uuid
             * @description Request correlation ID for distributed tracing
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            correlation_id: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when the error occurred
             * @example 2025-11-11T14:32:00Z
             */
            timestamp: string;
            /** @description Optional array of specific validation errors */
            errors?: {
                /** @example email */
                field?: string;
                /** @example Invalid email format */
                message?: string;
                /** @example INVALID_FORMAT */
                code?: string;
            }[];
        };
    };
    responses: {
        /** @description Internal server error */
        ServerError: {
            headers: {
                /** @description Request correlation ID for distributed tracing */
                "X-Correlation-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Unique request correlation ID for tracking */
        CorrelationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique request correlation ID for tracking */
                "X-Correlation-ID": components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "healthy" | "degraded" | "unhealthy";
                        /** Format: date-time */
                        timestamp: string;
                        services: {
                            /** @enum {string} */
                            database?: "up" | "down";
                            /** @enum {string} */
                            api?: "up" | "down";
                        };
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
