/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new investigation
         * @description Queue a new LLM-powered investigation job
         */
        post: operations["startInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigationId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get investigation status
         * @description Poll for the current status of an investigation job
         */
        get: operations["getInvestigationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InvestigationRequest: {
            /**
             * @description Type of entity to investigate
             * @enum {string}
             */
            entity_type: "transaction" | "reconciliation" | "attribution" | "platform";
            /** @description Unique identifier of the entity */
            entity_id: string;
            /**
             * @description Type of investigation to perform
             * @enum {string}
             */
            investigation_type: "discrepancy" | "anomaly" | "verification" | "root_cause";
            /** @description Additional context for the investigation */
            context?: {
                [key: string]: unknown;
            };
        };
        InvestigationStatusResponse: {
            /** @description Unique investigation identifier */
            investigation_id: string;
            /**
             * @description Current status of the investigation
             * @enum {string}
             */
            status: "queued" | "in_progress" | "completed" | "failed" | "cancelled";
            /** @description Progress percentage (0-100) */
            progress: number;
            /** @description Investigation results (present when completed) */
            result?: {
                findings?: {
                    type?: string;
                    /** @enum {string} */
                    severity?: "low" | "medium" | "high" | "critical";
                    description?: string;
                    confidence?: number;
                }[];
                recommendations?: string[];
            };
            /** @description Error details (present when failed) */
            error?: {
                code?: string;
                message?: string;
            };
            /**
             * Format: date-time
             * @description When the investigation was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the investigation was last updated
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startInvestigation: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationRequest"];
            };
        };
        responses: {
            /** @description Investigation queued successfully */
            202: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
        };
    };
    getInvestigationStatus: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string;
            };
            path: {
                /** @description Unique investigation identifier */
                investigationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investigation status retrieved */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
        };
    };
}
