/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/budget/optimization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize budget allocation
         * @description Get LLM-powered budget optimization recommendations
         */
        post: operations["optimizeBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BudgetOptimizationRequest: {
            /** @description Total budget amount to allocate */
            total_budget: number;
            /**
             * @description Currency code (ISO 4217)
             * @default USD
             */
            currency: string;
            /**
             * @description Time period for the budget allocation
             * @default monthly
             * @enum {string}
             */
            time_period: "daily" | "weekly" | "monthly" | "quarterly" | "yearly";
            platforms: {
                /** @description Platform identifier */
                name: string;
                /** @description Current budget allocation for this platform */
                current_allocation: number;
                /** @description Performance score (0-1) */
                performance_score?: number;
            }[];
            /**
             * @description Primary optimization objective
             * @default maximize_roi
             * @enum {string}
             */
            optimization_goal: "maximize_roi" | "minimize_cost" | "balance_growth" | "reduce_variance";
            /** @description Optional constraints for optimization */
            constraints?: {
                min_allocation_per_platform?: number;
                max_allocation_per_platform?: number;
                locked_platforms?: string[];
            };
        };
        BudgetOptimizationResponse: {
            /** @description Unique optimization identifier */
            optimization_id: string;
            /**
             * @description Status of the optimization
             * @enum {string}
             */
            status: "completed" | "partial" | "failed";
            recommendations: {
                /** @description Platform identifier */
                platform: string;
                /** @description Current budget allocation */
                current_allocation: number;
                /** @description Recommended new allocation */
                recommended_allocation: number;
                /** @description Percentage change from current */
                change_percentage?: number;
                /** @description LLM-generated explanation for the recommendation */
                rationale?: string;
            }[];
            /** @description Projected improvements from following recommendations */
            projected_improvement?: {
                /** @description Projected ROI increase percentage */
                roi_increase?: number;
                /** @description Projected revenue increase amount */
                revenue_increase?: number;
                /** @description Confidence score for the projection */
                confidence?: number;
            };
            /**
             * Format: date-time
             * @description When the optimization was created
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    optimizeBudget: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetOptimizationRequest"];
            };
        };
        responses: {
            /** @description Budget optimization completed */
            200: {
                headers: {
                    "X-Correlation-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOptimizationResponse"];
                };
            };
        };
    };
}
