/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/shopify/orders/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shopifyOrderCreated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/shopify/checkouts/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shopifyCheckoutUpdated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        ShopifyOrder: {
            id: number;
            order_number: number;
            total_price: string;
            subtotal_price?: string;
            total_tax?: string;
            currency?: string;
            created_at: string;
            confirmed?: boolean;
            financial_status?: "pending" | "paid" | "refunded" | "voided";
            note_attributes?: {
                name?: string;
                value?: string;
            }[];
            customer?: {
                id?: number;
                email?: string;
            };
            line_items?: {
                id?: number;
                title?: string;
                quantity?: number;
                price?: string;
            }[];
        };
        ShopifyCheckout: {
            token: string;
            total_price: string;
            subtotal_price?: string;
            currency?: string;
            abandoned_checkout_url?: string;
            note_attributes?: {
                name?: string;
                value?: string;
            }[];
        };
        SuccessResponse: {
            success: boolean;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export interface operations {
    shopifyOrderCreated: {
        parameters: {
            query?: never;
            header: {
                "X-Shopify-Hmac-SHA256": string;
                "X-Shopify-Shop-Domain": string;
                "X-Shopify-Topic": "orders/create";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopifyOrder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shopifyCheckoutUpdated: {
        parameters: {
            query?: never;
            header: {
                "X-Shopify-Hmac-SHA256": string;
                "X-Shopify-Shop-Domain": string;
                "X-Shopify-Topic": "checkouts/update";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopifyCheckout"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
}

export type $defs = Record<string, never>;
