/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/stripe/payment_intent.succeeded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stripePaymentIntentSucceeded"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe/checkout.session.completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stripeCheckoutSessionCompleted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        StripePaymentIntent: {
            id: string;
            object: "payment_intent";
            amount: number;
            amount_received: number;
            currency: string;
            status: "succeeded" | "processing" | "requires_payment_method" | "canceled";
            created: number;
            metadata?: Record<string, string>;
            customer?: string | null;
            payment_method?: string;
        };
        StripeCheckoutSession: {
            id: string;
            object: "checkout.session";
            amount_total: number;
            currency: string;
            status: "complete" | "expired" | "open";
            payment_status: "paid" | "unpaid" | "no_payment_required";
            customer?: string | null;
            customer_email?: string | null;
            metadata?: Record<string, string>;
            created: number;
        };
        StripeEvent: {
            id: string;
            object: "event";
            type: string;
            created: number;
            data: {
                object: components["schemas"]["StripePaymentIntent"] | components["schemas"]["StripeCheckoutSession"];
            };
            livemode: boolean;
        };
        SuccessResponse: {
            success: boolean;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export interface operations {
    stripePaymentIntentSucceeded: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StripeEvent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stripeCheckoutSessionCompleted: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StripeEvent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
}

export type $defs = Record<string, never>;
