import { POLICY_AUTHORITY_EXPLANATION } from '../lib/policyAuthorityLabels';

export const BUDGET_SIMULATION_COPY = {
  title: 'Budget Simulation',
  subtitle: 'Generate a policy-aware simulation proposal from verified revenue evidence.',
  metadataLine:
    'Impact figures are simulation proposals over verified revenue evidence — not executed platform changes or financial truth mutations.',
  policyBoundaryNotice:
    'Simulation proposals do not execute platform changes. Skeldir will show policy authority before any proposal can be submitted.',
  inputSectionLabel: 'Simulation inputs',
  readiness: {
    title: 'Simulation readiness',
    ready: 'Ready to generate',
    blocked: 'Simulation unavailable',
    partial: 'Partial evidence available',
    loading: 'Checking simulation sufficiency…',
    empty: 'Complete the required inputs to check simulation readiness.',
    error: 'Simulation readiness check failed. No financial truth was changed.',
  },
  gates: {
    minimumChannels: 'Minimum channels',
    verifiedConversions: 'Verified conversions',
    verifiedRevenueWindow: 'Verified revenue window',
    policyChecks: 'Policy checks',
    supplementalEvidence: 'Supplemental evidence',
    passed: 'Passed',
    available: 'Available',
    failed: 'Failed',
  },
  fields: {
    dateRange: 'Date range',
    spendConstraint: 'Spend constraint',
    objective: 'Objective',
    verifiedRevenueWindow: 'Required minimum verified revenue window',
    channelsIncluded: 'Channels included',
    required: 'Required',
    selectDateRange: 'Select date range',
    selectObjective: 'Select objective',
    selectChannels: 'Select channels',
    enterBudget: 'Enter budget amount',
    selectWindow: 'Select verified revenue window',
  },
  generate: {
    label: 'Generate simulation',
    loading: 'Generating simulation…',
    loadingProgress: 'Still generating simulation proposal…',
  },
  submit: {
    label: 'Submit proposal for certification',
    loading: 'Submitting proposal…',
    caption: 'No platform action is taken on submission.',
    successToast: 'Proposal submitted for certification.',
  },
  toast: {
    generateSuccess: 'Simulation generated. Review policy authority before submitting proposal.',
    generateError: 'Simulation generation failed. No financial truth was changed.',
    submitError: 'Proposal submission failed. No platform action was taken.',
  },
  staleBanner: 'Inputs changed. Regenerate simulation before submitting proposal.',
  inputAuthority: {
    title: 'Input authority',
    eligible: 'Eligible for simulation',
    ineligible: 'Not eligible for simulation',
    statusPartial: 'Partial evidence available',
    statusLoading: 'Checking eligibility',
    statusError: 'Eligibility check failed',
    statusEmpty: 'Awaiting inputs',
    introEligible: 'The current input state is eligible for simulation.',
    introIneligible: 'The current input state is not eligible for simulation.',
    introPartial:
      'Deterministic gates pass, but some probabilistic or benchmark evidence may be unavailable.',
    introLoading: 'Rechecking whether the current input state can support simulation.',
    introError: 'Simulation eligibility could not be verified. No financial truth was changed.',
    introEmpty: 'Complete the required inputs to evaluate simulation eligibility.',
    deterministicEvidence: 'Deterministic evidence present',
    verifiedChannels: 'Verified channels available',
    verifiedConversions: 'Verified conversions available',
    minimumChannelsRequired: 'Minimum channels required',
    channelsAvailable: 'Channels available',
    minimumConversionsRequired: 'Minimum verified conversions required',
    conversionsAvailable: 'Verified conversions available',
    trustApiState: 'Trust API state',
    actionAuthority: 'Action authority',
    submissionGated: 'Submission remains policy-gated',
    yes: 'Yes',
    no: 'No',
    operational: 'Operational',
    unavailable: 'Unavailable',
    generateAllowed: 'Generate simulation allowed',
    generateBlocked: 'Generate simulation blocked',
    actionBlocked: 'blocked',
  },
  policyAuthority: {
    title: 'Policy authority',
    approvalRequiredBody: POLICY_AUTHORITY_EXPLANATION.approvalRequired,
    proposalRequiredBody:
      'This simulation result can be submitted as a governed proposal. It does not execute platform changes.',
    blockedBody: 'Policy authority blocks proposal submission for this simulation.',
    simulationOnlyBody: 'This simulation can be reviewed but not submitted under current policy.',
  },
  auditArtifact: {
    title: 'Audit artifact status',
    written: 'Written',
    pending: 'Pending',
    unavailable: 'Unavailable',
    readyCaption: 'The audit artifact for this simulation is written and ready.',
    pendingCaption: 'Audit artifact is pending. Proposal submission is unavailable until written.',
    referenceLabel: 'Audit ref',
  },
  allocation: {
    comparisonLabel: 'Allocation comparison',
    current: 'Current allocation',
    simulated: 'Simulated allocation',
    total: 'Total',
  },
  expectedImpact: {
    title: 'Expected impact',
    expectedRevenue: 'expected verified revenue',
    blendedCac: 'Blended CAC',
    spendDelta: 'Spend delta',
    caption: 'Impact is based on verified revenue evidence from the included TrustEnvelopes.',
  },
  sourceEnvelopes: {
    caption: 'Source TrustEnvelopes used for this simulation',
    envelopeId: 'Envelope ID',
    channel: 'Channel',
    authority: 'Authority',
    contributionRole: 'Contribution role',
    verifiedRevenue: 'Verified revenue',
    open: 'Open',
    primary: 'Primary',
    supporting: 'Supporting',
  },
  resultSectionLabel: 'Simulation result',
} as const;

export const BUDGET_DETAIL_COPY = {
  titlePrefix: 'Budget simulation',
  subtitle: 'Review simulation assumptions, verified revenue basis, and policy authority before proposal submission.',
  metadataLine:
    'This surface presents a policy-gated simulation proposal over verified revenue evidence — not an executed platform change.',
  summary: {
    ariaLabel: 'Budget simulation summary',
    verifiedRevenue: 'Verified revenue basis',
    policyAuthority: 'Policy authority',
    confidence: 'Confidence',
    status: 'Simulation status',
    topAllocation: 'Largest projected share',
    reviewPolicy: 'Review policy',
    reviewConfidence: 'Review confidence',
    reviewAllocation: 'Review allocation',
    available: 'Available',
    unavailable: 'Unavailable',
  },
  sections: {
    assumptions: 'Input assumptions',
    confidence: 'Confidence / sparse-data state',
    benchmark: 'Benchmark context',
    policy: 'Policy authority',
    allocation: 'Projected budget allocation',
    risks: 'Risk caveats',
    audit: 'Audit reference',
  },
  status: {
    ready: 'Ready',
    blocked_insufficient_data: 'Unavailable — insufficient data',
    blocked_policy: 'Unavailable — policy',
  },
} as const;
