openapi: 3.1.0
info:
  title: Skeldir Common Components
  version: 1.0.0
  description: Shared components (security, headers, error schemas) for all Skeldir API contracts
servers: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication
  
  headers:
    X-Correlation-ID:
      description: Distributed tracing correlation ID for request tracking
      required: true
      schema:
        type: string
        format: uuid
        example: "550e8400-e29b-41d4-a716-446655440000"
    X-RateLimit-Limit:
      description: Maximum number of requests allowed in the current window
      schema:
        type: integer
        example: 100
    X-RateLimit-Remaining:
      description: Number of requests remaining in the current window
      schema:
        type: integer
        example: 95
    X-RateLimit-Reset:
      description: Unix timestamp when the rate limit window resets
      schema:
        type: integer
        format: int64
        example: 1609459200
  
  schemas:
    Problem:
      type: object
      required:
        - type
        - title
        - status
        - detail
      properties:
        type:
          type: string
          format: uri
          description: URI reference that identifies the problem type
          example: "https://api.skeldir.com/problems/validation-error"
        title:
          type: string
          description: Short, human-readable summary of the problem type
          example: "Validation Error"
        status:
          type: integer
          description: HTTP status code
          example: 400
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
          example: "The request body failed validation"
        instance:
          type: string
          format: uri
          description: URI reference that identifies the specific occurrence of the problem
          example: "/api/attribution/revenue/realtime"
        error_id:
          type: string
          format: uuid
          description: Unique identifier for this error occurrence (Skeldir extension)
          example: "550e8400-e29b-41d4-a716-446655440000"
        correlation_id:
          type: string
          format: uuid
          description: Correlation ID from the request header (Skeldir extension)
          example: "550e8400-e29b-41d4-a716-446655440000"
      example:
        type: "https://api.skeldir.com/problems/validation-error"
        title: "Validation Error"
        status: 400
        detail: "The request body failed validation"
        instance: "/api/attribution/revenue/realtime"
        error_id: "550e8400-e29b-41d4-a716-446655440000"
        correlation_id: "550e8400-e29b-41d4-a716-446655440000"
  
  responses:
    Unauthorized:
      description: Authentication required or invalid token
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            invalid_token:
              summary: Invalid or expired token
              value:
                type: "https://api.skeldir.com/problems/unauthorized"
                title: "Unauthorized"
                status: 401
                detail: "Invalid or expired authentication token"
                instance: "/api/attribution/revenue/realtime"
                error_id: "550e8400-e29b-41d4-a716-446655440000"
                correlation_id: "550e8400-e29b-41d4-a716-446655440000"
            missing_token:
              summary: Missing authentication token
              value:
                type: "https://api.skeldir.com/problems/unauthorized"
                title: "Unauthorized"
                status: 401
                detail: "Authentication token required"
                instance: "/api/attribution/revenue/realtime"
                error_id: "550e8400-e29b-41d4-a716-446655440000"
                correlation_id: "550e8400-e29b-41d4-a716-446655440000"
    
    TooManyRequests:
      description: Rate limit exceeded
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: "https://api.skeldir.com/problems/rate-limit-exceeded"
            title: "Too Many Requests"
            status: 429
            detail: "Rate limit exceeded. Please retry after the reset time."
            instance: "/api/attribution/revenue/realtime"
            error_id: "550e8400-e29b-41d4-a716-446655440000"
            correlation_id: "550e8400-e29b-41d4-a716-446655440000"
    
    InternalServerError:
      description: Internal server error
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: "https://api.skeldir.com/problems/internal-server-error"
            title: "Internal Server Error"
            status: 500
            detail: "An unexpected error occurred. Please contact support with the error_id."
            instance: "/api/attribution/revenue/realtime"
            error_id: "550e8400-e29b-41d4-a716-446655440000"
            correlation_id: "550e8400-e29b-41d4-a716-446655440000"






