openapi: 3.1.0
info:
  title: Skeldir Pagination Components
  version: 1.0.0
  description: Pagination parameters and envelope schemas for all Skeldir API contracts
servers: []
paths: {}
components:
  parameters:
    limit:
      name: limit
      in: query
      description: Maximum number of items to return per page
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50
      example: 50
    
    cursor:
      name: cursor
      in: query
      description: Cursor for pagination (base64-encoded pagination token)
      required: false
      schema:
        type: string
        format: base64
      example: "eyJvZmZzZXQiOjUwfQ=="
  
  schemas:
    PaginationMeta:
      type: object
      required:
        - cursor
        - limit
        - has_more
      properties:
        cursor:
          type: string
          format: base64
          description: Cursor for the next page (null if no more pages)
          nullable: true
          example: "eyJvZmZzZXQiOjEwMH0=="
        limit:
          type: integer
          description: Number of items per page
          example: 50
        has_more:
          type: boolean
          description: Whether there are more items available
          example: true
      example:
        cursor: "eyJvZmZzZXQiOjUwfQ=="
        limit: 50
        has_more: true






