openapi: 3.1.0
info:
  title: Skeldir Export API
  version: 1.0.0
  description: Data export endpoints for Skeldir Attribution Intelligence platform
servers:
  - url: https://api.skeldir.com
    description: Production server
  - url: http://localhost:4013
    description: Prism mock server for frontend development
paths:
  /api/export/revenue:
    get:
      operationId: exportRevenue
      tags:
        - Export
      summary: Export revenue data
      description: Export revenue data in CSV or JSON format with pagination and date range filtering
      security:
        - BearerAuth: []
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          schema:
            type: string
            format: uuid
          description: Distributed tracing correlation ID
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum:
              - csv
              - json
            default: json
          description: Export format (CSV or JSON)
        - $ref: '../../_common/v1/pagination.yaml#/components/parameters/limit'
        - $ref: '../../_common/v1/pagination.yaml#/components/parameters/cursor'
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date for revenue data (ISO 8601 format)
          example: "2025-01-01"
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date for revenue data (ISO 8601 format)
          example: "2025-11-10"
      responses:
        '200':
          description: Revenue data exported successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
            X-RateLimit-Limit:
              schema:
                type: integer
            X-RateLimit-Remaining:
              schema:
                type: integer
            X-RateLimit-Reset:
              schema:
                type: integer
                format: int64
          content:
            application/json:
              schema:
                type: object
                required:
                  - file_url
                  - tenant_id
                properties:
                  file_url:
                    type: string
                    format: uri
                    description: URL to download the exported file
                    example: "https://api.skeldir.com/exports/revenue_20251110.json"
                  tenant_id:
                    type: string
                    format: uuid
                    description: Tenant identifier
                    example: "550e8400-e29b-41d4-a716-446655440000"
              examples:
                json_export:
                  summary: JSON export
                  value:
                    file_url: "https://api.skeldir.com/exports/revenue_20251110.json"
                    tenant_id: "550e8400-e29b-41d4-a716-446655440000"
            text/csv:
              schema:
                type: string
                description: CSV file content
              examples:
                csv_export:
                  summary: CSV export
                  value: "date,revenue,channel\n2025-01-01,1000.50,google_search\n2025-01-02,1500.75,facebook_ads"
        '401':
          $ref: '../../_common/v1/components.yaml#/components/responses/Unauthorized'
        '429':
          $ref: '../../_common/v1/components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: '../../_common/v1/components.yaml#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../_common/v1/components.yaml#/components/securitySchemes/BearerAuth'
