openapi: 3.1.0
info:
  title: Skeldir Attribution API
  version: 2.0.0
  description: |
    Attribution Intelligence API - Realtime Revenue Counter and Attribution Data.
    Provides verified revenue metrics with statistical confidence scoring.

servers:
  - url: http://localhost:4011
    description: Prism Mock Server (Attribution)

security:
  - bearerAuth: []

paths:
  /api/attribution/revenue/realtime:
    get:
      summary: Get Realtime Revenue Counter
      description: |
        Polls realtime revenue metrics with 30-second cache TTL.
        Supports ETag-based caching with If-None-Match header for bandwidth optimization.
      operationId: getRealtimeRevenue
      tags:
        - Attribution
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
        - $ref: './_common/base.yaml#/components/parameters/IfNoneMatch'
      responses:
        '200':
          description: Revenue counter data returned successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
              description: Request correlation ID echoed back
            ETag:
              schema:
                type: string
              description: Entity tag for cache validation
            Cache-Control:
              schema:
                type: string
              description: Cache control directives
              example: max-age=30
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RealtimeRevenueCounter'
              example:
                total_revenue: 125430.50
                event_count: 1247
                last_updated: '2025-11-26T14:32:00Z'
                data_freshness_seconds: 5
                verified: true
                confidence_score: 0.94
                upgrade_notice: null
        '304':
          description: Not Modified - ETag matches, use cached data
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
            ETag:
              schema:
                type: string
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '429':
          $ref: './_common/base.yaml#/components/responses/RateLimitError'
        '500':
          $ref: './_common/base.yaml#/components/responses/ServerError'

  /api/attribution/channels:
    get:
      summary: Get Channel Attribution Data
      description: Returns attribution data broken down by marketing channel
      operationId: getChannelAttribution
      tags:
        - Attribution
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date for attribution window
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date for attribution window
      responses:
        '200':
          description: Channel attribution data
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - channels
                  - total_revenue
                  - date_range
                properties:
                  channels:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChannelAttribution'
                  total_revenue:
                    type: number
                    format: float
                  date_range:
                    type: object
                    properties:
                      start:
                        type: string
                        format: date
                      end:
                        type: string
                        format: date
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'

components:
  schemas:
    RealtimeRevenueCounter:
      type: object
      required:
        - total_revenue
        - event_count
        - last_updated
        - data_freshness_seconds
        - verified
      properties:
        total_revenue:
          type: number
          format: float
          description: Total verified revenue amount in USD
          example: 125430.50
        event_count:
          type: integer
          description: Number of revenue events tracked
          minimum: 0
          example: 1247
        last_updated:
          type: string
          format: date-time
          description: ISO 8601 timestamp of last data update
          example: '2025-11-26T14:32:00Z'
        data_freshness_seconds:
          type: integer
          description: Seconds since data was last refreshed
          minimum: 0
          example: 5
        verified:
          type: boolean
          description: Whether revenue is verified through payment reconciliation
          example: true
        confidence_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Statistical confidence score (0-1) for attribution accuracy
          example: 0.94
        upgrade_notice:
          type: string
          nullable: true
          description: Optional message about upgrading for more features
          example: Upgrade to Pro for historical analytics

    ChannelAttribution:
      type: object
      required:
        - channel_name
        - revenue
        - conversion_count
        - confidence_score
      properties:
        channel_name:
          type: string
          enum: [Meta, Google, TikTok, LinkedIn, Organic, Direct, Email, Referral]
          description: Marketing channel name
        revenue:
          type: number
          format: float
          description: Attributed revenue for this channel
        conversion_count:
          type: integer
          description: Number of conversions attributed to this channel
        confidence_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
          description: Statistical confidence in attribution accuracy
        spend:
          type: number
          format: float
          description: Marketing spend on this channel
        roas:
          type: number
          format: float
          description: Return on Ad Spend (revenue/spend)

  securitySchemes:
    bearerAuth:
      $ref: './_common/base.yaml#/components/securitySchemes/bearerAuth'
