openapi: 3.1.0
info:
  title: Skeldir Authentication API
  version: 2.0.0
  description: |
    User authentication and authorization endpoints.
    Provides JWT-based authentication with secure token refresh.
  contact:
    name: Skeldir Engineering
    email: engineering@skeldir.com
    url: https://skeldir.com

servers:
  - url: http://localhost:4010
    description: Prism Mock Server (Auth)

tags:
  - name: Authentication
    description: User authentication and authorization endpoints

security:
  - bearerAuth: []

paths:
  /api/auth/login:
    post:
      summary: User login
      description: Authenticate user with email and password, returns JWT tokens
      operationId: login
      tags:
        - Authentication
      security: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
            example:
              email: user@example.com
              password: securepassword123
      responses:
        '200':
          description: Login successful
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                  - refresh_token
                  - expires_in
                  - user
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  refresh_token:
                    type: string
                    description: JWT refresh token for obtaining new access tokens
                  expires_in:
                    type: integer
                    description: Token expiration time in seconds
                    example: 3600
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                      username:
                        type: string
              example:
                access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                expires_in: 3600
                user:
                  id: 550e8400-e29b-41d4-a716-446655440000
                  email: user@example.com
                  username: testuser
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './_common/base.yaml#/components/responses/ForbiddenError'
        '429':
          $ref: './_common/base.yaml#/components/responses/RateLimitError'

  /api/auth/refresh:
    post:
      summary: Refresh access token
      description: Exchange a valid refresh token for a new access token
      operationId: refreshToken
      tags:
        - Authentication
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: The refresh token from login response
      responses:
        '200':
          description: Token refreshed successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                  - expires_in
                properties:
                  access_token:
                    type: string
                    description: New JWT access token
                  refresh_token:
                    type: string
                    description: New refresh token (token rotation)
                  expires_in:
                    type: integer
                    description: Token expiration time in seconds
              example:
                access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                expires_in: 3600
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './_common/base.yaml#/components/responses/ForbiddenError'

  /api/auth/logout:
    post:
      summary: User logout
      description: Invalidate current session and tokens
      operationId: logout
      tags:
        - Authentication
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Logout successful
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: './_common/base.yaml#/components/schemas/SuccessResponse'
              example:
                success: true
                correlation_id: 00000000-0000-0000-0000-000000000000
                message: Session terminated
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './_common/base.yaml#/components/responses/ForbiddenError'

  /api/auth/verify:
    get:
      summary: Verify token validity
      description: Check if the current access token is valid
      operationId: verifyToken
      tags:
        - Authentication
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Token is valid
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - valid
                  - user_id
                properties:
                  valid:
                    type: boolean
                    example: true
                  user_id:
                    type: string
                    format: uuid
                  expires_at:
                    type: string
                    format: date-time
              example:
                valid: true
                user_id: 550e8400-e29b-41d4-a716-446655440000
                expires_at: '2025-11-26T15:30:00Z'
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './_common/base.yaml#/components/responses/ForbiddenError'

components:
  securitySchemes:
    bearerAuth:
      $ref: './_common/base.yaml#/components/securitySchemes/bearerAuth'
