openapi: 3.1.0
# B0.1 validation trigger - final fixes 50227e9
info:
  title: Skeldir Health Monitoring API
  version: 2.0.0
  description: |
    System health and status monitoring endpoints.
    Provides real-time health checks for all system components.
  contact:
    name: Skeldir Engineering
    email: engineering@skeldir.com
    url: https://skeldir.com

servers:
  - url: http://localhost:4014
    description: Prism Mock Server (Health)

tags:
  - name: Health
    description: System health and status monitoring endpoints

paths:
  /api/health:
    get:
      summary: Get system health status
      description: |
        Returns overall system health and status of individual services.
        No authentication required for basic health check.
      operationId: getHealthStatus
      tags:
        - Health
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
      responses:
        '200':
          description: System is healthy
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: healthy
                timestamp: '2025-11-26T14:30:00Z'
                version: 2.0.0
                services:
                  database: up
                  api: up
                  cache: up
                  queue: up
                uptime_seconds: 86400
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /api/health/detailed:
    get:
      summary: Get detailed system health
      description: Returns detailed health information including metrics (requires authentication)
      operationId: getDetailedHealth
      tags:
        - Health
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Detailed health information
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedHealthResponse'
              example:
                status: healthy
                timestamp: '2025-11-26T14:30:00Z'
                version: 2.0.0
                services:
                  database: up
                  api: up
                  cache: up
                  queue: up
                uptime_seconds: 86400
                metrics:
                  requests_per_minute: 1200
                  average_response_ms: 180.5
                  error_rate: 0.002
                  active_connections: 24
                database:
                  pool_size: 50
                  active_connections: 12
                  query_latency_ms: 12.3
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './_common/base.yaml#/components/responses/ForbiddenError'

  /api/health/ready:
    get:
      summary: Kubernetes readiness probe
      description: Indicates if the service is ready to accept traffic
      operationId: readinessProbe
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  ready:
                    type: boolean
                    example: true
              example:
                ready: true
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /api/health/live:
    get:
      summary: Kubernetes liveness probe
      description: Indicates if the service is alive and should not be restarted
      operationId: livenessProbe
      tags:
        - Health
      responses:
        '200':
          description: Service is alive
          content:
            application/json:
              schema:
                type: object
                properties:
                  alive:
                    type: boolean
                    example: true
              example:
                alive: true
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - services
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
          description: Overall system health status
        timestamp:
          type: string
          format: date-time
          description: Health check timestamp
        version:
          type: string
          description: API version
          example: '2.0.0'
        services:
          type: object
          description: Individual service statuses
          properties:
            database:
              type: string
              enum: [up, down, degraded]
            api:
              type: string
              enum: [up, down, degraded]
            cache:
              type: string
              enum: [up, down, degraded]
            queue:
              type: string
              enum: [up, down, degraded]
        uptime_seconds:
          type: integer
          description: Service uptime in seconds
          minimum: 0

    DetailedHealthResponse:
      allOf:
        - $ref: '#/components/schemas/HealthResponse'
        - type: object
          properties:
            metrics:
              type: object
              properties:
                requests_per_minute:
                  type: integer
                average_response_ms:
                  type: number
                  format: float
                error_rate:
                  type: number
                  format: float
                  minimum: 0
                  maximum: 1
                active_connections:
                  type: integer
            database:
              type: object
              properties:
                pool_size:
                  type: integer
                active_connections:
                  type: integer
                query_latency_ms:
                  type: number
                  format: float

  responses:
    ServiceUnavailable:
      description: Service is unavailable
      headers:
        X-Correlation-ID:
          schema:
            type: string
            format: uuid
          description: Request correlation ID for distributed tracing
      content:
        application/problem+json:
          schema:
            $ref: './_common/base.yaml#/components/schemas/ProblemDetails'

  securitySchemes:
    bearerAuth:
      $ref: './_common/base.yaml#/components/securitySchemes/bearerAuth'
