openapi: 3.1.0
info:
  title: Skeldir LLM Explanations API
  version: 1.0.0
  description: |
    Fast RAG endpoints for interactive explanations with sub-500ms p95 latency.
    Provides natural language explanations for attribution scores, budget recommendations,
    reconciliation discrepancies, and channel performance with deterministic citations.
  contact:
    name: Skeldir Engineering
    email: engineering@skeldir.com
    url: https://skeldir.com

servers:
  - url: http://localhost:4026
    description: Prism Mock Server (LLM Explanations)

tags:
  - name: LLM Explanations
    description: Natural language explanations with deterministic citations

security:
  - bearerAuth: []

paths:
  /api/v1/explain/{entity_type}/{entity_id}:
    get:
      summary: Get natural language explanation for any entity
      description: |
        Fast RAG endpoint for interactive explanations. Centaur architecture:
        retrieves deterministic data, synthesizes via LLM.
        Target latency: <500ms p95.
        Cost budget: $0.02 per explanation (Haiku-optimized).
      operationId: getEntityExplanation
      tags:
        - LLM Explanations
      security:
        - bearerAuth: []
      parameters:
        - name: entity_type
          in: path
          required: true
          description: Type of entity to explain
          schema:
            type: string
            enum:
              - attribution_score
              - budget_recommendation
              - reconciliation_discrepancy
              - channel_performance
        - name: entity_id
          in: path
          required: true
          description: Unique identifier for the entity
          schema:
            type: string
            format: uuid
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Explanation with citations and confidence scoring
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
              description: Request correlation ID echoed back
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityExplanation'
              example:
                explanation: "Your Facebook ROAS of $3.20 indicates strong performance because you have 90 days of stable conversion data with narrow confidence bounds ($2.95-$3.45). This outperforms your Google Ads ROAS of $2.10 by 52%."
                citations:
                  - metric: facebook_roas
                    value: 3.20
                    source: attribution_scores.roas
                  - metric: google_roas
                    value: 2.10
                    source: attribution_scores.roas
                confidence: high
                generated_at: '2025-12-04T02:30:00Z'
                cost_cents: 1.8
        '400':
          description: Invalid entity_type or entity_id format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExplanationError'
        '404':
          $ref: './_common/base.yaml#/components/responses/NotFoundError'
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '500':
          $ref: './_common/base.yaml#/components/responses/ServerError'
      x-latency-requirement: 500ms
      x-cost-budget: 0.02
      x-complexity-score: 5
      x-llm-usage: true
      x-deterministic-guarantee: false
      x-model-routing: haiku-first

components:
  schemas:
    EntityExplanation:
      type: object
      required:
        - explanation
        - citations
        - confidence
        - generated_at
      properties:
        explanation:
          type: string
          minLength: 100
          maxLength: 500
          description: Natural language explanation of the entity (150-300 words typical)
          example: "Your Facebook ROAS of $3.20 indicates strong performance because you have 90 days of stable conversion data with narrow confidence bounds ($2.95-$3.45)."
        citations:
          type: array
          description: References to deterministic data sources backing the explanation
          items:
            $ref: '#/components/schemas/Citation'
        confidence:
          type: string
          enum:
            - high
            - medium
            - low
          description: Explanation confidence based on data quality and recency
        generated_at:
          type: string
          format: date-time
          description: ISO 8601 timestamp when explanation was generated
        cost_cents:
          type: number
          format: float
          description: LLM API cost for this explanation (internal tracking)
          example: 1.8
          x-internal: true

    Citation:
      type: object
      required:
        - metric
        - value
        - source
      properties:
        metric:
          type: string
          description: Name of the metric being cited
          example: facebook_roas
        value:
          type: number
          description: The actual value of the metric
          example: 3.20
        source:
          type: string
          description: Database table.column reference for auditability
          example: attribution_scores.roas

    ExplanationError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: invalid_entity_type
        message:
          type: string
          description: Human-readable error message
          example: "entity_type must be one of: attribution_score, budget_recommendation, reconciliation_discrepancy, channel_performance"
        details:
          type: object
          description: Additional error context
          additionalProperties: true

  securitySchemes:
    bearerAuth:
      $ref: './_common/base.yaml#/components/securitySchemes/bearerAuth'
