openapi: 3.1.0
info:
  title: Skeldir Reconciliation API
  version: 2.0.0
  description: |
    Platform reconciliation status endpoints.
    Provides real-time connection status and data sync information for integrated platforms.

servers:
  - url: http://localhost:4012
    description: Prism Mock Server (Reconciliation)

security:
  - bearerAuth: []

paths:
  /api/reconciliation/status:
    get:
      summary: Get reconciliation status for all platforms
      description: |
        Returns the current connection and sync status for all integrated platforms.
        Includes verification status for payment providers.
      operationId: getReconciliationStatus
      tags:
        - Reconciliation
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      responses:
        '200':
          description: Reconciliation status for all platforms
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconciliationStatusResponse'
              example:
                platforms:
                  - platform_name: Shopify
                    connection_status: verified
                    last_sync: '2025-11-26T14:30:00Z'
                    events_processed: 1523
                    revenue_verified: 45230.00
                  - platform_name: Stripe
                    connection_status: verified
                    last_sync: '2025-11-26T14:28:00Z'
                    events_processed: 892
                    revenue_verified: 38120.50
                  - platform_name: Meta
                    connection_status: partial
                    last_sync: '2025-11-26T12:00:00Z'
                    error_message: API rate limit reached
                overall_status: partial
                last_full_sync: '2025-11-26T10:00:00Z'
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '500':
          $ref: './_common/base.yaml#/components/responses/ServerError'

  /api/reconciliation/platform/{platform_id}:
    get:
      summary: Get detailed status for a specific platform
      description: Returns detailed reconciliation information for a single platform
      operationId: getPlatformReconciliationStatus
      tags:
        - Reconciliation
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
        - name: platform_id
          in: path
          required: true
          schema:
            type: string
          description: Platform identifier
      responses:
        '200':
          description: Detailed platform reconciliation status
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformStatus'
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './_common/base.yaml#/components/responses/NotFoundError'

  /api/reconciliation/sync:
    post:
      summary: Trigger manual sync for platforms
      description: Initiates a manual synchronization for specified platforms
      operationId: triggerSync
      tags:
        - Reconciliation
      security:
        - bearerAuth: []
      parameters:
        - $ref: './_common/base.yaml#/components/parameters/CorrelationId'
        - $ref: './_common/base.yaml#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platforms:
                  type: array
                  items:
                    type: string
                  description: List of platform IDs to sync (empty = all platforms)
                full_sync:
                  type: boolean
                  default: false
                  description: Whether to perform a full historical sync
      responses:
        '202':
          description: Sync initiated
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - sync_id
                  - status
                  - estimated_completion
                properties:
                  sync_id:
                    type: string
                    format: uuid
                  status:
                    type: string
                    enum: [queued, in_progress]
                  estimated_completion:
                    type: string
                    format: date-time
        '401':
          $ref: './_common/base.yaml#/components/responses/UnauthorizedError'

components:
  schemas:
    ReconciliationStatusResponse:
      type: object
      required:
        - platforms
        - overall_status
      properties:
        platforms:
          type: array
          items:
            $ref: '#/components/schemas/PlatformStatus'
        overall_status:
          type: string
          enum: [verified, partial, pending, failed]
          description: Aggregate status across all platforms
        last_full_sync:
          type: string
          format: date-time
          description: Timestamp of last complete sync across all platforms

    PlatformStatus:
      type: object
      required:
        - platform_name
        - connection_status
        - last_sync
      properties:
        platform_name:
          type: string
          enum: [Meta, Google, TikTok, LinkedIn, Shopify, WooCommerce, Stripe, PayPal]
          description: Platform identifier
        connection_status:
          type: string
          enum: [verified, partial, pending, failed, disconnected]
          description: Current connection status
        last_sync:
          type: string
          format: date-time
          description: Timestamp of last successful sync
        events_processed:
          type: integer
          minimum: 0
          description: Total events processed from this platform
        revenue_verified:
          type: number
          format: float
          description: Total verified revenue from this platform
        error_message:
          type: string
          description: Error description if connection is not fully verified
        next_scheduled_sync:
          type: string
          format: date-time
          description: When the next automatic sync is scheduled

  securitySchemes:
    bearerAuth:
      $ref: './_common/base.yaml#/components/securitySchemes/bearerAuth'
