import type { ChannelTrustGroupBy, ChannelTrustRow } from './types';
import { sortChannelTrustRows } from './channelTrustDisplay';

function platformRow(
  channelId: string,
  partial: Omit<ChannelTrustRow, 'rowId' | 'channelId' | 'detailHref'> & { detailHref?: string },
): ChannelTrustRow {
  return {
    rowId: channelId,
    channelId,
    detailHref: `/app/channels?expand=${channelId}`,
    ...partial,
  };
}

const PLATFORM_ROWS: ChannelTrustRow[] = sortChannelTrustRows([
  platformRow('ch_meta_ads', {
    axisLabel: 'Meta Ads',
    claimSource: 'meta_ads',
    campaignClass: 'paid_social',
    commerceRail: 'direct',
    verifiedRevenueMinor: 10_288_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 860,
    modelAgreementTier: 'medium',
    benchmarkValue: '3.8% ROAS',
    benchmarkEvidenceClass: 'live_empirical',
    policyAuthority: 'approval_required',
  }),
  platformRow('ch_google_ads', {
    axisLabel: 'Google Ads',
    claimSource: 'google_ads',
    campaignClass: 'paid_search',
    commerceRail: 'organic',
    verifiedRevenueMinor: 12_842_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 940,
    modelAgreementTier: 'high',
    benchmarkValue: '4.2% CVR',
    benchmarkEvidenceClass: 'tenant_longitudinal',
    policyAuthority: 'blocked',
  }),
  platformRow('ch_linkedin', {
    axisLabel: 'LinkedIn',
    claimSource: 'linkedin_ads',
    campaignClass: 'branded',
    commerceRail: 'referral',
    verifiedRevenueMinor: 1_864_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 200,
    modelAgreementTier: 'high',
    benchmarkValue: '2.1% CVR',
    benchmarkEvidenceClass: 'historical_prior',
    policyAuthority: 'proposal_required',
  }),
  platformRow('ch_organic_search', {
    axisLabel: 'Organic Search',
    claimSource: 'organic_search',
    campaignClass: 'paid_search',
    commerceRail: 'organic',
    verifiedRevenueMinor: 2_418_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 200,
    modelAgreementTier: 'high',
    benchmarkValue: '5.4% CVR',
    benchmarkEvidenceClass: 'live_empirical',
    policyAuthority: 'simulation_only',
  }),
  platformRow('ch_tiktok_ads', {
    axisLabel: 'TikTok Ads',
    claimSource: 'tiktok_ads',
    campaignClass: 'creator',
    commerceRail: 'direct',
    verifiedRevenueMinor: 0n,
    currencyCode: 'USD',
    discrepancyRateBps: null,
    modelAgreementTier: 'low',
    benchmarkValue: null,
    benchmarkEvidenceClass: 'unavailable',
    benchmarkUnavailableReason:
      'Insufficient cross-tenant signal. Exact bucket suppressed for privacy.',
    policyAuthority: 'blocked',
  }),
]);

const CAMPAIGN_CLASS_ROWS: ChannelTrustRow[] = sortChannelTrustRows([
  {
    rowId: 'cc_paid_search',
    channelId: 'cc_paid_search',
    axisLabel: 'Paid Search',
    claimSource: 'google_ads',
    campaignClass: 'paid_search',
    commerceRail: 'organic',
    verifiedRevenueMinor: 15_260_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 720,
    modelAgreementTier: 'high',
    benchmarkValue: '4.2% CVR',
    benchmarkEvidenceClass: 'tenant_longitudinal',
    policyAuthority: 'approval_required',
  },
  {
    rowId: 'cc_paid_social',
    channelId: 'cc_paid_social',
    axisLabel: 'Paid Social',
    claimSource: 'meta_ads',
    campaignClass: 'paid_social',
    commerceRail: 'direct',
    verifiedRevenueMinor: 10_288_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 860,
    modelAgreementTier: 'medium',
    benchmarkValue: '3.8% ROAS',
    benchmarkEvidenceClass: 'live_empirical',
    policyAuthority: 'blocked',
  },
  {
    rowId: 'cc_creator',
    channelId: 'cc_creator',
    axisLabel: 'Creator',
    claimSource: 'tiktok_ads',
    campaignClass: 'creator',
    commerceRail: 'referral',
    verifiedRevenueMinor: 842_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 1100,
    modelAgreementTier: 'conflict',
    benchmarkValue: '1.9% CVR',
    benchmarkEvidenceClass: 'historical_prior',
    policyAuthority: 'proposal_required',
  },
  {
    rowId: 'cc_branded',
    channelId: 'cc_branded',
    axisLabel: 'Branded',
    claimSource: 'linkedin_ads',
    campaignClass: 'branded',
    commerceRail: 'referral',
    verifiedRevenueMinor: 1_864_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 200,
    modelAgreementTier: 'high',
    benchmarkValue: '2.1% CVR',
    benchmarkEvidenceClass: 'historical_prior',
    policyAuthority: 'simulation_only',
  },
  {
    rowId: 'cc_affiliate',
    channelId: 'cc_affiliate',
    axisLabel: 'Affiliate',
    claimSource: 'google_ads',
    campaignClass: 'affiliate',
    commerceRail: 'email',
    verifiedRevenueMinor: 520_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 150,
    modelAgreementTier: 'low',
    benchmarkValue: null,
    benchmarkEvidenceClass: 'unavailable',
    benchmarkUnavailableReason:
      'Insufficient cross-tenant signal. Exact bucket suppressed for privacy.',
    policyAuthority: 'blocked',
  },
]);

const COMMERCE_RAIL_ROWS: ChannelTrustRow[] = sortChannelTrustRows([
  {
    rowId: 'cr_organic',
    channelId: 'cr_organic',
    axisLabel: 'Organic',
    claimSource: 'google_ads',
    campaignClass: 'paid_search',
    commerceRail: 'organic',
    verifiedRevenueMinor: 14_680_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 480,
    modelAgreementTier: 'high',
    benchmarkValue: '5.4% CVR',
    benchmarkEvidenceClass: 'live_empirical',
    policyAuthority: 'approval_required',
  },
  {
    rowId: 'cr_direct',
    channelId: 'cr_direct',
    axisLabel: 'Direct',
    claimSource: 'meta_ads',
    campaignClass: 'paid_social',
    commerceRail: 'direct',
    verifiedRevenueMinor: 9_120_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 920,
    modelAgreementTier: 'medium',
    benchmarkValue: '3.8% ROAS',
    benchmarkEvidenceClass: 'tenant_longitudinal',
    policyAuthority: 'blocked',
  },
  {
    rowId: 'cr_referral',
    channelId: 'cr_referral',
    axisLabel: 'Referral',
    claimSource: 'linkedin_ads',
    campaignClass: 'creator',
    commerceRail: 'referral',
    verifiedRevenueMinor: 2_104_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 640,
    modelAgreementTier: 'low',
    benchmarkValue: '2.1% CVR',
    benchmarkEvidenceClass: 'historical_prior',
    policyAuthority: 'proposal_required',
  },
  {
    rowId: 'cr_email',
    channelId: 'cr_email',
    axisLabel: 'Email',
    claimSource: 'email',
    campaignClass: 'affiliate',
    commerceRail: 'email',
    verifiedRevenueMinor: 942_000n,
    currencyCode: 'USD',
    discrepancyRateBps: 210,
    modelAgreementTier: 'high',
    benchmarkValue: '6.1% CVR',
    benchmarkEvidenceClass: 'live_empirical',
    policyAuthority: 'simulation_only',
  },
]);

export const CHANNEL_TRUST_SNAPSHOT_BY_AXIS: Record<ChannelTrustGroupBy, ChannelTrustRow[]> = {
  platform: PLATFORM_ROWS,
  campaign_class: CAMPAIGN_CLASS_ROWS,
  commerce_rail: COMMERCE_RAIL_ROWS,
};

/** Default platform-axis snapshot for aggregate substrate. */
export const COMMAND_CENTER_CHANNEL_ROWS: ChannelTrustRow[] = PLATFORM_ROWS;

export function channelTrustRowsForAxis(groupBy: ChannelTrustGroupBy): ChannelTrustRow[] {
  return CHANNEL_TRUST_SNAPSHOT_BY_AXIS[groupBy];
}
