openapi: 3.1.0
info:
  title: Skeldir Health API
  version: 1.0.0
  description: Health check endpoints for Skeldir Attribution Intelligence platform
servers:
  - url: https://api.skeldir.com
    description: Production server
  - url: http://localhost:4014
    description: Prism mock server for frontend development
paths:
  /api/health:
    get:
      operationId: healthCheck
      tags:
        - Health
      summary: Health check endpoint
      description: Returns the health status of the API service. Used by mock healthchecks and FE smoke tests.
      security: []
      parameters: []
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - timestamp
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    description: Current server timestamp
                    example: "2025-11-10T14:30:00Z"
              examples:
                healthy:
                  summary: Service healthy
                  value:
                    status: "healthy"
                    timestamp: "2025-11-10T14:30:00Z"
components: {}
