export const BILLING_COPY = {
  pageTitle: 'Billing',
  pageDescription:
    'Manage your commercial account plan and billing history. Billing affects account access and plan management only.',
  trustBoundaryTitle: 'Commercial account — not financial truth',
  trustBoundaryBody:
    'Billing affects commercial account access and plan management. Billing does not create verified revenue. Billing does not change TrustEnvelope truth. Billing does not rewrite audit evidence. Billing does not prove or disprove platform claims.',
  planSectionTitle: 'Current plan',
  statusSectionTitle: 'Billing status',
  paymentMethodTitle: 'Payment method',
  paymentMethodNone: 'No payment method on file.',
  paymentMethodSummary: (brand: string, last4: string) => `${brand} ending in ${last4}`,
  invoicesTitle: 'Billing history',
  invoicesEmpty: 'No invoices yet for this workspace.',
  manageBilling: 'Manage billing',
  manageBillingPending: 'Opening billing portal…',
  manageBillingConfirmTitle: 'Open hosted billing portal?',
  manageBillingConfirmBody:
    'Plan updates and payment changes are handled in Skeldir’s hosted billing portal. No card details are entered inside Skeldir.',
  manageBillingConfirmAction: 'Continue to billing portal',
  manageBillingCancel: 'Cancel',
  manageBillingExternalHint: 'You will leave Skeldir to manage billing securely.',
  portalUnavailable: 'Billing portal is temporarily unavailable. Try again later.',
  networkError: 'Unable to reach billing services. No account changes were made.',
  permissionDenied: 'You do not have permission to view or manage billing for this workspace.',
  loading: 'Loading billing information…',
  renewalLabel: 'Renews',
  trialEndsLabel: 'Trial ends',
  statusActive: 'Active',
  statusTrialing: 'Trialing',
  statusPastDue: 'Past due',
  statusCanceled: 'Canceled',
  statusPaused: 'Paused',
  invoiceStatusPaid: 'Paid',
  invoiceStatusOpen: 'Open',
  invoiceStatusVoid: 'Void',
  viewerReadOnlyNotice: 'You can view plan details. Contact an owner or admin to change billing.',
} as const;
