# generated by datamodel-codegen:
#   filename:  attribution.yaml

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field


class RealtimeRevenueCounter(BaseModel):
    total_revenue: Annotated[float, Field(example=125430.5)]
    """
    Total verified revenue amount in USD
    """
    event_count: Annotated[int, Field(example=1247, ge=0)]
    """
    Number of revenue events tracked
    """
    last_updated: Annotated[datetime, Field(example='2025-11-26T14:32:00Z')]
    """
    ISO 8601 timestamp of last data update
    """
    data_freshness_seconds: Annotated[int, Field(example=5, ge=0)]
    """
    Seconds since data was last refreshed
    """
    verified: Annotated[bool, Field(example=True)]
    """
    Whether revenue is verified through payment reconciliation
    """
    tenant_id: Annotated[str, Field(example='00000000-0000-0000-0000-000000000000')]
    """
    Tenant identifier associated with the revenue data
    """
    confidence_score: Annotated[
        Optional[float], Field(example=0.94, ge=0.0, le=1.0)
    ] = None
    """
    Statistical confidence score (0-1) for attribution accuracy
    """
    upgrade_notice: Annotated[
        Optional[str], Field(example='Upgrade to Pro for historical analytics')
    ] = None
    """
    Optional message about upgrading for more features
    """


class ChannelName(Enum):
    """
    Marketing channel name
    """

    Meta = 'Meta'
    Google = 'Google'
    TikTok = 'TikTok'
    LinkedIn = 'LinkedIn'
    Organic = 'Organic'
    Direct = 'Direct'
    Email = 'Email'
    Referral = 'Referral'


class ChannelAttribution(BaseModel):
    channel_name: ChannelName
    """
    Marketing channel name
    """
    revenue: float
    """
    Attributed revenue for this channel
    """
    conversion_count: int
    """
    Number of conversions attributed to this channel
    """
    confidence_score: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Statistical confidence in attribution accuracy
    """
    spend: Optional[float] = None
    """
    Marketing spend on this channel
    """
    roas: Optional[float] = None
    """
    Return on Ad Spend (revenue/spend)
    """


class Platform(Enum):
    """
    Supported platform identifier
    """

    google_ads = 'google_ads'
    meta_ads = 'meta_ads'
    tiktok_ads = 'tiktok_ads'
    linkedin_ads = 'linkedin_ads'
    stripe = 'stripe'
    paypal = 'paypal'
    shopify = 'shopify'
    woocommerce = 'woocommerce'


class PlatformConnectionStatus(Enum):
    """
    Connection lifecycle state
    """

    pending = 'pending'
    active = 'active'
    disabled = 'disabled'


class PlatformConnectionUpsertRequest(BaseModel):
    platform: Platform
    platform_account_id: Annotated[str, Field(description='Platform account identifier (e.g., Google Ads customer ID)')]
    status: Optional[PlatformConnectionStatus] = None
    metadata: Optional[dict] = None


class PlatformConnectionResponse(BaseModel):
    id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    platform_account_id: str
    status: PlatformConnectionStatus
    created_at: datetime
    updated_at: datetime


class PlatformCredentialUpsertRequest(BaseModel):
    platform: Platform
    platform_account_id: str
    access_token: Annotated[str, Field(description='Access token (never returned once stored)')]
    refresh_token: Optional[str] = None
    expires_at: Optional[datetime] = None
    scope: Optional[str] = None
    token_type: Optional[str] = None


class PlatformCredentialStatus(Enum):
    """
    Credential storage status
    """

    stored = 'stored'
    expired = 'expired'
    missing = 'missing'


class PlatformCredentialStatusResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    platform_account_id: str
    status: PlatformCredentialStatus
    expires_at: Optional[datetime] = None
    updated_at: datetime


class ProviderOAuthLifecycleState(Enum):
    not_connected = 'not_connected'
    authorization_pending = 'authorization_pending'
    connected = 'connected'
    expired = 'expired'
    revoked = 'revoked'
    reconnect_required = 'reconnect_required'


class ProviderRefreshResultState(Enum):
    not_attempted = 'not_attempted'
    fresh = 'fresh'
    due = 'due'
    in_progress = 'in_progress'
    succeeded = 'succeeded'
    failed = 'failed'


class ProviderOAuthAuthorizeRequest(BaseModel):
    platform_account_id: str
    redirect_uri: str
    requested_scopes: Optional[list[str]] = None


class ProviderOAuthAuthorizeResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    lifecycle_state: ProviderOAuthLifecycleState
    authorization_url: str
    state_reference: str
    state_expires_at: datetime
    data_freshness_seconds: Annotated[int, Field(ge=0)]
    last_updated: datetime


class ProviderOAuthCallbackResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    platform_account_id: str
    lifecycle_state: ProviderOAuthLifecycleState
    refresh_state: ProviderRefreshResultState
    data_freshness_seconds: Annotated[int, Field(ge=0)]
    last_updated: datetime


class ProviderOAuthStatusResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    platform_account_id: str
    lifecycle_state: ProviderOAuthLifecycleState
    refresh_state: ProviderRefreshResultState
    expires_at: Optional[datetime] = None
    scope: Optional[str] = None
    data_freshness_seconds: Annotated[int, Field(ge=0)]
    last_updated: datetime


class ProviderOAuthDisconnectReason(Enum):
    user_initiated = 'user_initiated'
    provider_revoked = 'provider_revoked'
    security_event = 'security_event'
    tenant_offboarding = 'tenant_offboarding'


class ProviderOAuthDisconnectRequest(BaseModel):
    reason: ProviderOAuthDisconnectReason


class ProviderOAuthDisconnectResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    lifecycle_state: ProviderOAuthLifecycleState
    disconnected_at: datetime
    data_freshness_seconds: Annotated[int, Field(ge=0)]
    last_updated: datetime


class ProviderLifecycleErrorCode(Enum):
    provider_not_connected = 'provider_not_connected'
    provider_expired = 'provider_expired'
    provider_revoked = 'provider_revoked'
    provider_scope_insufficient = 'provider_scope_insufficient'
    provider_rate_limited = 'provider_rate_limited'
    provider_transport_failure = 'provider_transport_failure'


class ProviderOAuthRefreshStateResponse(BaseModel):
    tenant_id: Annotated[str, Field(pattern=r'^[0-9a-fA-F-]{36}$')]
    platform: Platform
    lifecycle_state: ProviderOAuthLifecycleState
    refresh_state: ProviderRefreshResultState
    next_refresh_due_at: Optional[datetime] = None
    last_refresh_attempt_at: Optional[datetime] = None
    last_refresh_success_at: Optional[datetime] = None
    last_error_code: Optional[ProviderLifecycleErrorCode] = None
    data_freshness_seconds: Annotated[int, Field(ge=0)]
    last_updated: datetime


# Alias for CI compatibility (must be a class definition to match workflow grep pattern)
class RealtimeRevenueResponse(RealtimeRevenueCounter):
    """Alias for RealtimeRevenueCounter to match CI expectations."""
    pass
