# generated by datamodel-codegen:
#   filename:  auth.bundled.yaml

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal, Optional
from uuid import UUID

from pydantic import AnyUrl, BaseModel, EmailStr, Field, SecretStr


class LoginRequest(BaseModel):
    email: Annotated[EmailStr, Field(example='user@example.com')]
    password: Annotated[SecretStr, Field(example='securePassword123')]
    tenant_id: Annotated[UUID, Field(example='550e8400-e29b-41d4-a716-446655440000')]


class User(BaseModel):
    id: UUID
    email: EmailStr
    username: str


class LoginResponse(BaseModel):
    access_token: str
    """
    JWT access token
    """
    refresh_token: str
    """
    Opaque refresh token
    """
    expires_in: Annotated[int, Field(example=3600)]
    """
    Token expiration time in seconds
    """
    user: User
    """
    Authenticated user profile for the session
    """
    token_type: Annotated[str, Field(example='Bearer')]
    """
    Token type
    """


class RefreshRequest(BaseModel):
    refresh_token: str
    """
    Opaque refresh token
    """
    tenant_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None


class RefreshResponse(BaseModel):
    access_token: str
    """
    New JWT access token
    """
    refresh_token: str
    """
    New opaque refresh token
    """
    expires_in: Annotated[int, Field(example=3600)]
    """
    Token expiration time in seconds
    """
    token_type: Annotated[str, Field(example='Bearer')]
    """
    Token type
    """


class LogoutResponse(BaseModel):
    message: Annotated[str, Field(example='Logout successful')]


class Problem(BaseModel):
    type: Annotated[
        AnyUrl, Field(example='https://api.skeldir.com/problems/validation-error')
    ]
    """
    URI reference that identifies the problem type
    """
    title: Annotated[str, Field(example='Validation Error')]
    """
    Short, human-readable summary of the problem type
    """
    status: Annotated[int, Field(example=400)]
    """
    HTTP status code
    """
    detail: Annotated[str, Field(example='The request body failed validation')]
    """
    Human-readable explanation specific to this occurrence
    """
    instance: Annotated[
        Optional[AnyUrl], Field(example='/api/attribution/revenue/realtime')
    ] = None
    """
    URI reference that identifies the specific occurrence of the problem
    """
    error_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Unique identifier for this error occurrence (Skeldir extension)
    """
    correlation_id: Annotated[
        Optional[UUID], Field(example='550e8400-e29b-41d4-a716-446655440000')
    ] = None
    """
    Correlation ID from the request header (Skeldir extension)
    """


class AdminTokenCutoffRequest(BaseModel):
    user_id: UUID
    tokens_invalid_before: datetime | None = None


class AdminTokenCutoffResponse(BaseModel):
    success: bool
    correlation_id: UUID
    tenant_id: UUID
    user_id: UUID
    tokens_invalid_before: datetime
    message: str


class AdminWhoAmIResponse(BaseModel):
    success: bool
    correlation_id: UUID
    tenant_id: UUID
    user_id: UUID
    role: Literal['admin', 'manager', 'viewer']


class AdminUpdateMembershipRoleRequest(BaseModel):
    user_id: UUID
    role: Literal['admin', 'manager', 'viewer']


class AdminUpdateMembershipRoleResponse(BaseModel):
    success: bool
    correlation_id: UUID
    tenant_id: UUID
    user_id: UUID
    role: Literal['admin', 'manager', 'viewer']
    tokens_invalid_before: datetime
    revoked_existing_tokens: bool
    message: str
