export const GOVERNANCE_COPY = {
  teamPageTitle: 'Team settings',
  teamPageDescription:
    'Manage who can access tenant-scoped product surfaces. Team roles inform human access.',
  policyPageTitle: 'Policy authority',
  policyPageDescription:
    'Configure policy authority for future action-bearing surfaces. This does not execute actions or create audit proof.',
  permissionDeniedTitle: 'Permission denied',
  permissionDeniedBody:
    'Your role cannot manage this governance surface. Contact a workspace owner or admin.',
  permissionDeniedRecovery: 'Return to app frame',
  unknownRoleError: 'Unknown team role returned. Access controls are blocked until resolved.',
  unknownScopeError: 'Unknown agent scope returned. Credential cannot be trusted.',
  inviteNotAvailable:
    'Member invitations are not yet available in this environment. Contact support to add teammates.',
  teamTableCaption: 'Workspace team members',
  policyModeLabel: 'Policy mode',
  policyConfigureButton: 'Configure',
  policySaveButton: 'Save policy',
  policySaving: 'Saving policy…',
  policySaveFailed: 'Policy save failed. No policy action was executed.',
  policyCategoryLabels: {
    revenue_reads: 'Revenue reads',
    attribution_reads: 'Attribution reads',
    confidence_reads: 'Confidence reads',
    budget_simulation: 'Budget simulation',
    budget_proposal: 'Budget proposal',
    budget_execution: 'Budget execution',
    external_export: 'External export',
    agent_api_access: 'Agent API access',
  } as const,
  roleLabels: {
    owner: 'Owner',
    admin: 'Admin',
    manager: 'Manager',
    viewer: 'Viewer',
    billing_only: 'Billing only',
    unknown_role: 'Unknown role',
  } as const,
  memberStatusLabels: {
    active: 'Active',
    invited: 'Invited',
    suspended: 'Suspended',
    removed: 'Removed',
  } as const,
  agentSecretPlaceholder: 'skeldir_agent_key_redacted',
  autoExecuteBudgetCeiling: 'Budget ceiling (minor units)',
  autoExecuteCooldown: 'Cooldown period (hours)',
  autoExecuteHysteresis: 'Hysteresis threshold (%)',
  validation: {
    nameRequired: 'Name is required.',
    expirationRequired: 'Expiration is required (1–365 days).',
    expirationInvalid: 'Expiration must be between 1 and 365 days.',
    scopesRequired: 'Select at least one allowed scope.',
    rateLimitRequired: 'Rate limit is required (1–1000 per minute).',
    rateLimitInvalid: 'Rate limit must be between 1 and 1000 per minute.',
    allowedIpInvalid: 'Enter valid IPv4 addresses separated by commas.',
    acknowledgementRequired: 'Read-only trust-data acknowledgement is required.',
  },
} as const;
