import type { ChannelOverviewRowDTO } from '../ledger/types';
import { buildChannelCompositeId } from './channelIds';

/**
 * Six channel-trust rows — each row is one attribution-channel × claim-source intersection.
 * Claim source (who sent the claim) and attribution channel (traffic type) are never collapsed.
 */
export const CHANNELS_OVERVIEW_FIXTURES: ChannelOverviewRowDTO[] = [
  {
    channelId: buildChannelCompositeId('paid_search', 'google_ads'),
    channelName: 'Paid Search',
    attributionChannel: 'paid_search',
    claimSource: 'google_ads',
    commerceSource: 'shopify',
    verifiedRevenueMinor: 42_846_000n,
    claimedRevenueMinor: 42_846_000n,
    currencyCode: 'USD',
    discrepancyClass: 'within_tolerance',
    discrepancyRateBps: 100,
    discrepancyStatus: 'within_tolerance',
    attributionModelAgreement: '96.2%',
    bayesianStatusKey: 'healthy',
    bayesianStabilityLabel: 'Stable ±4.1%',
    benchmarkStatusKey: 'stable',
    benchmarkPositionLabel: 'Above benchmark',
    confidence: {
      status: 'available',
      intervalLower: 0.85,
      intervalUpper: 0.96,
      methodOrContext: 'Channel aggregate posterior',
    },
    benchmark: {
      status: 'available',
      evidenceClass: 'tenant_longitudinal',
      coverageClass: 'rolled_up',
      decisionSafeBenchmark: 'Above benchmark',
    },
    relatedClaimsCount: 48,
    relatedEnvelopeCount: 12,
    auditReference: 'aud_ch_paid_search_google',
    policyAuthority: 'approval_required',
    actionability: 'proposal_required',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
  {
    channelId: buildChannelCompositeId('paid_social', 'meta_ads'),
    channelName: 'Paid Social',
    attributionChannel: 'paid_social',
    claimSource: 'meta_ads',
    commerceSource: 'shopify',
    verifiedRevenueMinor: 25_614_000n,
    claimedRevenueMinor: 31_140_000n,
    currencyCode: 'USD',
    discrepancyClass: 'flagged',
    discrepancyRateBps: 1840,
    discrepancyStatus: 'flagged',
    attributionModelAgreement: '88.4%',
    bayesianStatusKey: 'healthy',
    bayesianStabilityLabel: 'Stable ±3.2%',
    benchmarkStatusKey: 'stable',
    benchmarkPositionLabel: 'Within benchmark',
    confidence: {
      status: 'available',
      intervalLower: 0.78,
      intervalUpper: 0.91,
      methodOrContext: 'Channel aggregate posterior',
    },
    benchmark: {
      status: 'available',
      evidenceClass: 'tenant_longitudinal',
      coverageClass: 'rolled_up',
      decisionSafeBenchmark: 'Within benchmark',
    },
    relatedClaimsCount: 36,
    relatedEnvelopeCount: 9,
    auditReference: 'aud_ch_paid_social_meta',
    policyAuthority: 'blocked',
    actionability: 'observe_only',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
  {
    channelId: buildChannelCompositeId('creator', 'meta_ads'),
    channelName: 'Creator Partnerships',
    attributionChannel: 'creator',
    claimSource: 'meta_ads',
    commerceSource: 'stripe',
    verifiedRevenueMinor: 8_493_000n,
    claimedRevenueMinor: 8_493_000n,
    currencyCode: 'USD',
    discrepancyClass: 'within_tolerance',
    discrepancyRateBps: 0,
    discrepancyStatus: 'within_tolerance',
    attributionModelAgreement: '72.1%',
    bayesianStatusKey: 'degraded',
    bayesianStabilityLabel: 'CI unavailable; sample volume below threshold',
    benchmarkStatusKey: 'attention_needed',
    benchmarkPositionLabel: 'Coverage insufficient',
    confidence: {
      status: 'unavailable',
      reason: 'CI unavailable; sample volume below threshold',
    },
    benchmark: {
      status: 'unavailable',
      reason: 'No defensible benchmark exists for this segment yet.',
    },
    relatedClaimsCount: 8,
    relatedEnvelopeCount: 2,
    auditReference: 'aud_ch_creator_meta',
    policyAuthority: 'blocked',
    actionability: 'observe_only',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
  {
    channelId: buildChannelCompositeId('email_lifecycle', 'email'),
    channelName: 'Email / Lifecycle',
    attributionChannel: 'email_lifecycle',
    claimSource: 'email',
    commerceSource: 'shopify',
    verifiedRevenueMinor: 51_288_000n,
    claimedRevenueMinor: 51_288_000n,
    currencyCode: 'USD',
    discrepancyClass: 'within_tolerance',
    discrepancyRateBps: 0,
    discrepancyStatus: 'within_tolerance',
    attributionModelAgreement: '94.8%',
    bayesianStatusKey: 'healthy',
    bayesianStabilityLabel: 'Stable ±2.8%',
    benchmarkStatusKey: 'stable',
    benchmarkPositionLabel: 'Above benchmark',
    confidence: {
      status: 'available',
      intervalLower: 0.9,
      intervalUpper: 0.97,
      methodOrContext: 'Channel aggregate posterior',
    },
    benchmark: {
      status: 'available',
      evidenceClass: 'tenant_longitudinal',
      coverageClass: 'exact_bucket',
      decisionSafeBenchmark: 'Above benchmark',
    },
    relatedClaimsCount: 52,
    relatedEnvelopeCount: 14,
    auditReference: 'aud_ch_email_lifecycle',
    policyAuthority: 'simulation_only',
    actionability: 'observe_only',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
  {
    channelId: buildChannelCompositeId('organic_search', 'organic_search'),
    channelName: 'Organic Search',
    attributionChannel: 'organic_search',
    claimSource: 'organic_search',
    commerceSource: 'shopify',
    verifiedRevenueMinor: 19_374_000n,
    claimedRevenueMinor: 19_570_000n,
    currencyCode: 'USD',
    discrepancyClass: 'within_tolerance',
    discrepancyRateBps: 100,
    discrepancyStatus: 'within_tolerance',
    attributionModelAgreement: '91.0%',
    bayesianStatusKey: 'healthy',
    bayesianStabilityLabel: 'Stable ±2.1%',
    benchmarkStatusKey: 'stable',
    benchmarkPositionLabel: 'Within tolerance',
    confidence: {
      status: 'available',
      intervalLower: 0.82,
      intervalUpper: 0.93,
      methodOrContext: 'Channel aggregate posterior',
    },
    benchmark: {
      status: 'available',
      evidenceClass: 'tenant_longitudinal',
      coverageClass: 'rolled_up',
      decisionSafeBenchmark: 'Within tolerance',
    },
    relatedClaimsCount: 22,
    relatedEnvelopeCount: 6,
    auditReference: 'aud_ch_organic_search',
    policyAuthority: 'proposal_required',
    actionability: 'proposal_required',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
  {
    channelId: buildChannelCompositeId('affiliate', 'meta_ads'),
    channelName: 'Affiliate',
    attributionChannel: 'affiliate',
    claimSource: 'meta_ads',
    commerceSource: 'stripe',
    verifiedRevenueMinor: 12_136_000n,
    claimedRevenueMinor: 12_136_000n,
    currencyCode: 'USD',
    discrepancyClass: 'within_tolerance',
    discrepancyRateBps: 0,
    discrepancyStatus: 'within_tolerance',
    attributionModelAgreement: '86.5%',
    bayesianStatusKey: 'healthy',
    bayesianStabilityLabel: 'Stable ±3.5%',
    benchmarkStatusKey: 'stable',
    benchmarkPositionLabel: 'Within benchmark',
    confidence: {
      status: 'available',
      intervalLower: 0.8,
      intervalUpper: 0.9,
      methodOrContext: 'Channel aggregate posterior',
    },
    benchmark: {
      status: 'available',
      evidenceClass: 'tenant_longitudinal',
      coverageClass: 'rolled_up',
      decisionSafeBenchmark: 'Within benchmark',
    },
    relatedClaimsCount: 14,
    relatedEnvelopeCount: 4,
    auditReference: 'aud_ch_affiliate_meta',
    policyAuthority: 'auto_executable_within_policy',
    actionability: 'proposal_required',
    futureDetailAffordance: 'detail_blocked_level_8',
  },
];
