export const CHANNELS_OVERVIEW_COPY = {
  title: 'Channels',
  subtitle: 'Verified channel performance from TrustEnvelope-backed claims.',
  metadataLine:
    'Revenue shown here is verified commerce evidence unless explicitly marked as platform-reported claim data.',
  metricBasis: {
    groupLabel: 'Revenue view',
    verified: 'Verified revenue',
    platformClaim: 'Platform-reported revenue',
    platformWarning: 'Platform-reported revenue is a claim source, not verified truth.',
    platformDisabledTooltip:
      'No platform claims have arrived yet. Skeldir can verify commerce events now and compare claims after ad sources connect.',
  },
  filters: {
    dateRange: 'Date range',
    attributionChannel: 'Attribution channel',
    claimSource: 'Claim source',
    commerceSource: 'Commerce source',
    revenueReliability: 'Revenue Reliability',
    bayesianStatus: 'Bayesian status',
    benchmarkStatus: 'Benchmark status',
    actionAuthority: 'Action authority',
    searchPlaceholder: 'Search channels',
    clearFilters: 'Clear filters',
  },
  summary: {
    highestVerifiedRevenue: 'Highest verified revenue',
    largestDiscrepancy: 'Largest discrepancy',
    lowestConfidence: 'Lowest confidence',
    bestActionReady: 'Best action-ready channel',
    openChannel: 'Open channel',
    confidenceDegraded: 'Confidence degraded',
    aboveBenchmark: 'Above benchmark',
  },
  table: {
    sectionTitle: 'Channel trust',
    caption:
      'Channel trust table showing attribution channel, claim source, verified revenue, claimed revenue, discrepancy, revenue reliability, Bayesian status, benchmark status, and action authority.',
    attributionChannel: 'Attribution channel',
    claimSource: 'Claim source',
    channel: 'Attribution channel',
    verifiedRevenue: 'Verified revenue',
    claimedRevenue: 'Claimed revenue',
    discrepancyRate: 'Discrepancy rate',
    revenueReliability: 'Revenue Reliability',
    bayesianStatus: 'Bayesian status',
    benchmarkStatus: 'Benchmark status',
    actionAuthority: 'Action authority',
    open: 'Details',
    rowsPerPage: 'Rows per page',
    empty: 'No channel trust data available.',
    filteredEmpty: 'No channels match these filters.',
    updating: 'Updating channel results…',
    loadingProgress: 'Loading channel trust data…',
    viewDetails: 'View details',
    hideDetails: 'Hide details',
  },
  pagination: {
    range: (start: number, end: number, total: number) => `${start}–${end} of ${total}`,
  },
} as const;
