"""Canonical deterministic attribution semantics surfaces."""

from app.attribution.semantics import (
    ATTRIBUTION_SEMANTICS_VERSION,
    CONVERSION_EVENT_TYPES,
    DETERMINISTIC_DEFAULT_LOOKBACK_DAYS,
    TOUCHPOINT_EVENT_TYPES,
    AttributionInputRow,
    AttributionOutputRow,
    DeterministicReplayIdentity,
    classify_event_type,
    compute_effective_replay_window,
    digest_canonical_payloads,
    normalize_lookback_days,
    session_scope_identity,
)
from app.attribution.strategy_kernel import (
    DETERMINISTIC_BASELINE_MODEL,
    FIRST_TOUCH_MODEL,
    LAST_TOUCH_MODEL,
    LINEAR_MODEL,
    STRATEGY_MODEL_TYPES,
    SUPPORTED_DETERMINISTIC_MODEL_TYPES,
    TIME_DECAY_MODEL,
    build_channel_allocations_for_conversion,
    canonical_model_type,
)

__all__ = [
    "ATTRIBUTION_SEMANTICS_VERSION",
    "CONVERSION_EVENT_TYPES",
    "DETERMINISTIC_DEFAULT_LOOKBACK_DAYS",
    "TOUCHPOINT_EVENT_TYPES",
    "AttributionInputRow",
    "AttributionOutputRow",
    "DeterministicReplayIdentity",
    "classify_event_type",
    "compute_effective_replay_window",
    "digest_canonical_payloads",
    "normalize_lookback_days",
    "session_scope_identity",
    "DETERMINISTIC_BASELINE_MODEL",
    "FIRST_TOUCH_MODEL",
    "LAST_TOUCH_MODEL",
    "LINEAR_MODEL",
    "TIME_DECAY_MODEL",
    "SUPPORTED_DETERMINISTIC_MODEL_TYPES",
    "STRATEGY_MODEL_TYPES",
    "canonical_model_type",
    "build_channel_allocations_for_conversion",
]
