openapi: 3.1.0
info:
  title: Skeldir PayPal Webhook API
  version: 1.0.0
  description: PayPal webhook ingestion endpoints for Skeldir Attribution Intelligence platform
servers:
  - url: https://api.skeldir.com
    description: Production server
  - url: http://localhost:4018
    description: Prism mock server for frontend development
paths:
  /webhooks/paypal/payment/sale/completed:
    post:
      operationId: paypalSaleCompleted
      tags:
        - Webhooks
        - PayPal
      summary: PayPal sale completed webhook
      description: |
        Receives PayPal sale completed webhooks for revenue attribution.
        
        **Security**: This endpoint validates PayPal webhook signatures using the PAYPAL-AUTH-ALGO, PAYPAL-CERT-URL, and PAYPAL-TRANSMISSION-SIG headers.
        The webhook secret must be configured in the tenant settings. PayPal uses RSA-SHA256 signature verification.
        
        **Privacy**: All PII (payer email, payer information, shipping address) is stripped from the payload before persistence.
        No storage of personally identifiable information occurs. Only session-scoped data is retained for attribution purposes.
        Session IDs are ephemeral (30-minute inactivity timeout) and are NOT used for cross-session tracking.
      security: []
      parameters:
        - name: PAYPAL-AUTH-ALGO
          in: header
          required: true
          schema:
            type: string
          description: PayPal signature algorithm (typically SHA256withRSA)
        - name: PAYPAL-CERT-URL
          in: header
          required: true
          schema:
            type: string
            format: uri
          description: URL to PayPal certificate for signature verification
        - name: PAYPAL-TRANSMISSION-SIG
          in: header
          required: true
          schema:
            type: string
          description: PayPal webhook signature for verification
        - name: X-Correlation-ID
          in: header
          required: false
          schema:
            type: string
            format: uuid
          description: Distributed tracing correlation ID (generated if not provided)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: |
                PayPal sale webhook payload. Note: PII fields (payer email, payer information, shipping address)
                are stripped before persistence. Only transaction ID, amount, currency, and create_time are retained.
              properties:
                id:
                  type: string
                  description: PayPal transaction ID (used for idempotency)
                amount:
                  type: object
                  description: Transaction amount object
                  properties:
                    total:
                      type: string
                      description: Total amount as string (will be converted to cents)
                    currency:
                      type: string
                      description: Currency code
                create_time:
                  type: string
                  format: date-time
                  description: Transaction creation timestamp
      responses:
        '200':
          description: Webhook processed successfully
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                required:
                  - acknowledged
                  - event_id
                properties:
                  acknowledged:
                    type: boolean
                    example: true
                  event_id:
                    type: string
                    description: Internal event ID for tracking
                    example: "evt_550e8400e29b41d4a716446655440000"
              examples:
                success:
                  summary: Webhook acknowledged
                  value:
                    acknowledged: true
                    event_id: "evt_550e8400e29b41d4a716446655440000"
        '400':
          description: Invalid webhook payload or signature
          headers:
            X-Correlation-ID:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '../../../_common/v1/components.yaml#/components/schemas/Problem'
              examples:
                invalid_signature:
                  summary: Invalid PayPal signature
                  value:
                    type: "https://api.skeldir.com/problems/invalid-webhook-signature"
                    title: "Invalid Webhook Signature"
                    status: 400
                    detail: "PayPal webhook signature validation failed"
                    instance: "/webhooks/paypal/payment/sale/completed"
                    error_id: "550e8400-e29b-41d4-a716-446655440000"
                    correlation_id: "550e8400-e29b-41d4-a716-446655440000"
        '401':
          $ref: '../../../_common/v1/components.yaml#/components/responses/Unauthorized'
components: {}
