openapi: 3.1.0
info:
  title: Skeldir Common Parameters
  version: 1.0.0
  description: Reusable path and query parameters for all Skeldir API contracts
servers: []
paths: {}
components:
  parameters:
    idempotency_key:
      name: X-Idempotency-Key
      in: header
      description: Idempotency key to prevent duplicate processing (UUID format)
      required: true
      schema:
        type: string
        format: uuid
      example: "550e8400-e29b-41d4-a716-446655440000"
    
    tenant_id:
      name: tenant_id
      in: path
      description: Tenant identifier from authentication context (extracted from JWT, not user-provided)
      required: true
      schema:
        type: string
        format: uuid
      example: "550e8400-e29b-41d4-a716-446655440000"

