"""B2.3 revenue verification semantic authority package."""

from .semantic_authority import (
    ALLOWED_DELAYED_ARRIVAL_FORBIDDEN_COLUMNS,
    ALLOWED_DELAYED_ARRIVAL_REQUIRED_COLUMNS,
    ALLOWED_DELAYED_ARRIVAL_TOPOLOGY_TABLE,
    B23DiscrepancyClass,
    B23DownstreamSemanticProjection,
    B23Verdict,
    CanonicalReferenceResult,
    CanonicalizationStatus,
    PrecedenceResolution,
    build_validated_downstream_projection,
    classify_payment_adjustment_support,
    canonicalize_attribution_commerce_reference,
    canonicalize_verified_commerce_reference,
    get_b23_p0_performance_thresholds,
    map_b23_discrepancy_for_downstream,
    map_b23_verdict_for_downstream,
    resolve_canonical_match_key,
    validate_delayed_arrival_topology_binding,
    validate_delayed_arrival_strategy,
    validate_delayed_arrival_topology,
    validate_downstream_projection_payload,
)

__all__ = [
    "ALLOWED_DELAYED_ARRIVAL_FORBIDDEN_COLUMNS",
    "ALLOWED_DELAYED_ARRIVAL_REQUIRED_COLUMNS",
    "ALLOWED_DELAYED_ARRIVAL_TOPOLOGY_TABLE",
    "B23DiscrepancyClass",
    "B23DownstreamSemanticProjection",
    "B23Verdict",
    "CanonicalReferenceResult",
    "CanonicalizationStatus",
    "PrecedenceResolution",
    "build_validated_downstream_projection",
    "classify_payment_adjustment_support",
    "canonicalize_attribution_commerce_reference",
    "canonicalize_verified_commerce_reference",
    "get_b23_p0_performance_thresholds",
    "map_b23_discrepancy_for_downstream",
    "map_b23_verdict_for_downstream",
    "resolve_canonical_match_key",
    "validate_delayed_arrival_topology_binding",
    "validate_delayed_arrival_strategy",
    "validate_delayed_arrival_topology",
    "validate_downstream_projection_payload",
]
