import type { ActionDirective } from './types/actionDirective';
import type { ChannelAttributionRow } from './types/channelAttribution';
import type { RevenueDiscrepancyAlertModel } from './types/revenueDiscrepancy';

export const MOCK_DATA = {
  dateRange: { preset: '30d', label: 'Last 30 days' },
  currency: 'USD',
  attributionModel: 'bayesian',

  trustBand: {
    verifiedRevenue: {
      rawValue: 97450,
      status: 'verified' as const,
      source: 'Stripe',
      lastUpdatedLabel: '4 min ago',
    },
    integrityScore: {
      score: 87,
    },
    dataFreshness: {
      lastSyncMinutesAgo: 2,
      syncHistory: [
        'Stripe — 2 min ago (full)',
        'Google Ads — 6 min ago',
        'Meta — 6 min ago',
      ],
    },
  },

  kpiGrid: {
    blendedCpl: {
      label: 'Blended CPL',
      value: '$29.00',
      trend: {
        direction: 'down' as const,
        value: '↓ 17%',
        sentiment: 'positive' as const,
        comparisonHint: 'Versus prior 30 days — lower CPL is better',
      },
      context: '$53.79 for paid channels',
      confidenceRange: {
        lower: 25.5,
        upper: 32.4,
        estimate: 29,
        lowerLabel: '$25.50',
        upperLabel: '$32.40',
        bucket: 'narrow' as const,
        actionImplication: 'Safe to act — uncertainty is narrow',
      },
    },
    leadToCustomer: {
      label: 'Lead → Customer',
      value: '15.01%',
      trend: {
        direction: 'up' as const,
        value: '↑ 7%',
        sentiment: 'positive' as const,
        comparisonHint: 'Compared to prior 30 days',
      },
      confidenceRange: {
        lower: 12.1,
        upper: 17.9,
        estimate: 15.01,
        lowerLabel: '12.1%',
        upperLabel: '17.9%',
        bucket: 'medium' as const,
        actionImplication: 'Monitor — medium-width interval',
      },
    },
    blendedCac: {
      label: 'Blended CAC',
      value: '$193.17',
      trend: {
        direction: 'down' as const,
        value: '↓ 23%',
        sentiment: 'positive' as const,
        comparisonHint: 'Versus prior 30 days — lower CAC is better',
      },
      confidenceRange: {
        lower: 165,
        upper: 228,
        estimate: 193.17,
        lowerLabel: '$165',
        upperLabel: '$228',
        bucket: 'narrow' as const,
        actionImplication: 'Safe to act',
      },
    },
    monthlyVerifiedRevenue: {
      label: 'Monthly Verified Revenue',
      value: '$387,000',
      trend: {
        direction: 'up' as const,
        value: '↑ 4.2%',
        sentiment: 'positive' as const,
        comparisonHint: 'Last 30 days vs prior 30 days',
      },
      context: 'Verified — last 30d',
      verifiedStatus: 'verified' as const,
    },
  },

  directives: [
    {
      id: 'd1',
      priority: 1,
      headline: 'Decrease Facebook spend by 15% to prevent ROAS decay',
      projectedOutcomeText: 'Estimated outcome: +$12K monthly revenue',
      confidenceRange: {
        lower: 10.2,
        upper: 13.8,
        estimate: 12,
        bucket: 'narrow' as const,
        lowerLabel: '$10.2K',
        upperLabel: '$13.8K',
        actionImplication: 'Safe to act on this data',
      },
      drivers: [
        'Facebook ROAS declining 3 consecutive weeks',
        'Google Search has 20% headroom at current spend',
      ],
      primaryAction: { label: 'Review & Approve', route: '/budget', asyncJobRequired: true },
      secondaryAction: { label: 'Dismiss', type: 'dismiss' as const },
      status: 'pending' as const,
      createdAt: '2026-03-21T17:00:00.000Z',
      relativeTime: '2 hours ago',
    },
    {
      id: 'd2',
      priority: 2,
      headline: 'Increase Google Search by $5K to capture headroom',
      projectedOutcomeText: '',
      confidenceRange: null,
      drivers: [],
      primaryAction: { label: 'View Details', route: '/channels/google_ads' },
      secondaryAction: undefined,
      status: 'pending' as const,
      createdAt: '2026-03-20T12:00:00.000Z',
      relativeTime: 'Yesterday',
    },
    {
      id: 'd3',
      priority: 3,
      headline: 'Winter promo reallocation — applied',
      projectedOutcomeText: '',
      confidenceRange: null,
      drivers: [],
      primaryAction: { label: 'View', route: '/budget' },
      secondaryAction: undefined,
      status: 'completed' as const,
      createdAt: '2026-03-18T10:00:00.000Z',
      relativeTime: '3 days ago',
    },
  ] as ActionDirective[],

  activeJobs: [
    {
      jobId: 'seed_j1',
      type: 'budget_optimization',
      label: 'Budget Optimizer',
      status: 'running' as const,
      elapsedSeconds: 45,
      durationSeconds: 60,
      statusMessage: 'Calculating optimal allocation…',
    },
    {
      jobId: 'seed_j2',
      type: 'data_backfill',
      label: 'Data Backfill (Meta Ads)',
      status: 'running' as const,
      elapsedSeconds: 10,
      durationSeconds: 30,
      statusMessage: 'Processing 30 days of historical data…',
    },
    {
      jobId: 'seed_j3',
      type: 'sync',
      label: 'Google Ads sync',
      status: 'complete' as const,
      statusMessage: 'Channel data refreshed.',
    },
  ],

  channels: [
    {
      channelId: 'meta',
      channelName: 'Facebook Ads',
      platform: 'meta',
      spend: '$22,400',
      verifiedRevenue: '$71,680',
      verifiedStatus: 'verified',
      verificationSource: 'Stripe',
      lastVerifiedLabel: '4 min ago',
      roas: {
        estimate: 3.2,
        lower: 2.8,
        upper: 3.6,
        bucket: 'narrow',
        formattedEstimate: '3.20',
        actionImplication: 'Safe to act — uncertainty is narrow',
      },
      confidence: 'narrow',
      confidenceActionImplication: 'Safe to act on this data',
      trend: {
        direction: 'down',
        label: '↓ 5%',
        sortValue: -5,
        comparisonHint: 'Versus prior 30 days',
      },
      attributionMethod: 'bayesian',
    },
    {
      channelId: 'google_ads',
      channelName: 'Google Ads',
      platform: 'google_ads',
      spend: '$15,000',
      verifiedRevenue: '$48,750',
      verifiedStatus: 'verified',
      verificationSource: 'Stripe',
      lastVerifiedLabel: '6 min ago',
      roas: {
        estimate: 3.25,
        lower: 2.9,
        upper: 3.6,
        bucket: 'narrow',
        formattedEstimate: '3.25',
        actionImplication: 'Safe to act — uncertainty is narrow',
      },
      confidence: 'narrow',
      confidenceActionImplication: 'Safe to act on this data',
      trend: {
        direction: 'up',
        label: '↑ 8%',
        sortValue: 8,
        comparisonHint: 'Versus prior 30 days',
      },
      attributionMethod: 'bayesian',
    },
    {
      channelId: 'linkedin',
      channelName: 'LinkedIn Ads',
      platform: 'linkedin',
      spend: '$8,000',
      verifiedRevenue: '$17,600',
      verifiedStatus: 'partial',
      verificationSource: 'Stripe + platform',
      lastVerifiedLabel: '1h ago',
      roas: {
        estimate: 2.2,
        lower: 1.6,
        upper: 2.8,
        bucket: 'medium',
        formattedEstimate: '2.20',
        actionImplication: 'Monitor — medium-width interval',
      },
      confidence: 'medium',
      confidenceActionImplication: 'Monitor before shifting spend',
      trend: {
        direction: 'down',
        label: '↓ 3%',
        sortValue: -3,
        comparisonHint: 'Compared to prior 30 days',
      },
      attributionMethod: 'bayesian',
    },
    {
      channelId: 'tiktok',
      channelName: 'TikTok Ads',
      platform: 'tiktok',
      spend: '$5,000',
      verifiedRevenue: '$12,500',
      verifiedStatus: 'unverified',
      verificationSource: '—',
      lastVerifiedLabel: 'Not synced',
      roas: {
        estimate: 2.5,
        lower: 1.6,
        upper: 3.4,
        bucket: 'wide',
        formattedEstimate: '2.50',
        actionImplication: 'Treat as directional — wide interval',
      },
      confidence: 'wide',
      confidenceActionImplication: 'Do not optimize solely on this ROAS until data quality improves',
      trend: {
        direction: 'up',
        label: '↑ 12%',
        sortValue: 12,
        comparisonHint: 'Versus prior 30 days',
      },
      attributionMethod: 'bayesian',
    },
    {
      channelId: 'pinterest',
      channelName: 'Pinterest Ads',
      platform: 'pinterest',
      spend: '$2,400',
      verifiedRevenue: '$7,450',
      verifiedStatus: 'verified',
      verificationSource: 'Stripe',
      lastVerifiedLabel: '12 min ago',
      roas: {
        estimate: 2.8,
        lower: 1.4,
        upper: 4.2,
        bucket: 'wide',
        formattedEstimate: '2.80',
        actionImplication: 'Wide interval — validate with experiments',
      },
      confidence: 'wide',
      confidenceActionImplication: 'Validate with holdout tests before scaling',
      trend: {
        direction: 'neutral',
        label: '— 0%',
        sortValue: 0,
        comparisonHint: 'Flat vs prior 30 days',
      },
      attributionMethod: 'bayesian',
    },
  ] as ChannelAttributionRow[],

  /** Full-width alert below Trust Band when |discrepancy| exceeds policy threshold. */
  revenueDiscrepancyAlert: {
    visible: true,
    primaryPlatformName: 'Facebook',
    claimedRevenueFormatted: '$52,300',
    verifiedRevenueFormatted: '$43,800',
    verifiedSource: 'Stripe',
    discrepancyPct: -16.2,
    otherPlatformsCount: 2,
  } satisfies RevenueDiscrepancyAlertModel,

  attributionWeights: {
    channels: [
      { channelId: 'google_ads', channelName: 'Google', weight: 0.342, weightFormatted: '34.2%', color: '#3B82F6' },
      { channelId: 'meta', channelName: 'Meta', weight: 0.221, weightFormatted: '22.1%', color: '#8B5CF6' },
      { channelId: 'tiktok', channelName: 'TikTok', weight: 0.184, weightFormatted: '18.4%', color: '#F59E0B' },
      { channelId: 'linkedin', channelName: 'LinkedIn', weight: 0.128, weightFormatted: '12.8%', color: '#10B981' },
      { channelId: 'pinterest', channelName: 'Pinterest', weight: 0.125, weightFormatted: '12.5%', color: '#EF4444' },
    ],
  },
};
