"""B2.6 semantic authority boundary.

P1 deliberately exports contract identity plus the positive
coverage-origin admission seam and the legacy quarantine record.
Reconciliation state, computation, workers, APIs, exports, and
TrustEnvelope fields begin in later dependency-ordered phases.
"""

from .coverage_authority import (
    B23_SOVEREIGN_COVERAGE_PRODUCER,
    CANONICAL_ADMISSION_MODULE,
    CANONICAL_ADMITTER,
    CANONICAL_COVERAGE_LAW,
    CANONICAL_LOADER,
    CANONICAL_PROVENANCE_MODEL,
    CANONICAL_RESOLVER,
    CANONICAL_SCOPE_VERIFIER,
    CANONICAL_SEALED_TYPE,
    GOVERNED_CANONICAL_SINK_NAMES,
    CanonicalCoverageAuthorityError,
    CanonicalCoverageScope,
    CanonicalVerificationCoverage,
    admit_canonical_verification_coverage,
    independent_coverage_percent,
    is_governed_canonical_sink,
    load_canonical_verification_coverage,
    require_canonical_scope,
    require_governed_canonical_sink,
    resolve_canonical_coverage,
    to_diagnostic_dict,
)
from .legacy_quarantine import (
    LEGACY_NON_AUTHORITATIVE_MODULES,
    LEGACY_NON_AUTHORITATIVE_RELATIONS,
    LEGACY_NON_AUTHORITATIVE_ROUTE_PATHS,
    LEGACY_QUARANTINE_ENFORCEMENT,
    LEGACY_QUARANTINE_NOTE,
    LEGACY_QUARANTINE_STATUS,
    LegacyAuthorityError,
    is_canonical_b26_authority,
    mark_legacy_diagnostic,
    refuse_legacy_as_canonical,
)
from .semantic_contract import (
    B26_DISCREPANCY_TAXONOMY_V1,
    B26_KNOWN_AUTHORITY_CLASSES,
    B26_P1_CONTRACT_VERSION,
    B26_P1_SEMANTIC_CONTRACT_PATH,
    B26_P1_SUPERSEDES_VERSION,
    B26_REQUIRED_DISCREPANCY_REASONS,
    B26_REQUIRED_FUTURE_INSERTION_SEAM,
    B26_REQUIRED_SCOPE_DISPOSITIONS,
    B26_REQUIRED_TRUTH_STATE_VOCABULARY,
    B26_SUCCESSOR_STATUS_AUTHORIZED,
    B26_SUCCESSOR_STATUS_NONE,
    SemanticContractError,
    SemanticContractIdentity,
    load_b26_p1_semantic_contract,
    semantic_contract_identity,
)

__all__ = [
    "B23_SOVEREIGN_COVERAGE_PRODUCER",
    "B26_DISCREPANCY_TAXONOMY_V1",
    "B26_KNOWN_AUTHORITY_CLASSES",
    "B26_P1_CONTRACT_VERSION",
    "B26_P1_SEMANTIC_CONTRACT_PATH",
    "B26_P1_SUPERSEDES_VERSION",
    "B26_REQUIRED_DISCREPANCY_REASONS",
    "B26_REQUIRED_FUTURE_INSERTION_SEAM",
    "B26_REQUIRED_SCOPE_DISPOSITIONS",
    "B26_REQUIRED_TRUTH_STATE_VOCABULARY",
    "B26_SUCCESSOR_STATUS_AUTHORIZED",
    "B26_SUCCESSOR_STATUS_NONE",
    "CANONICAL_ADMISSION_MODULE",
    "CANONICAL_ADMITTER",
    "CANONICAL_COVERAGE_LAW",
    "CANONICAL_LOADER",
    "CANONICAL_PROVENANCE_MODEL",
    "CANONICAL_RESOLVER",
    "CANONICAL_SCOPE_VERIFIER",
    "CANONICAL_SEALED_TYPE",
    "CanonicalCoverageAuthorityError",
    "CanonicalCoverageScope",
    "CanonicalVerificationCoverage",
    "GOVERNED_CANONICAL_SINK_NAMES",
    "LEGACY_NON_AUTHORITATIVE_MODULES",
    "LEGACY_NON_AUTHORITATIVE_RELATIONS",
    "LEGACY_NON_AUTHORITATIVE_ROUTE_PATHS",
    "LEGACY_QUARANTINE_ENFORCEMENT",
    "LEGACY_QUARANTINE_NOTE",
    "LEGACY_QUARANTINE_STATUS",
    "LegacyAuthorityError",
    "SemanticContractError",
    "SemanticContractIdentity",
    "admit_canonical_verification_coverage",
    "independent_coverage_percent",
    "is_canonical_b26_authority",
    "is_governed_canonical_sink",
    "load_b26_p1_semantic_contract",
    "load_canonical_verification_coverage",
    "mark_legacy_diagnostic",
    "refuse_legacy_as_canonical",
    "require_canonical_scope",
    "require_governed_canonical_sink",
    "resolve_canonical_coverage",
    "semantic_contract_identity",
    "to_diagnostic_dict",
]
