import type { ChannelData, AvailableChannel } from "./types";

/** Interface 7 — single limit for roster size and multi-select (chip bar + table). */
export const MAX_COMPARISON_CHANNELS = 6;

export const INITIAL_CHANNELS: ChannelData[] = [
  {
    channelId: "google_ads",
    channelName: "Google Ads",
    platform: "google_ads",
    colorIndex: 1,
    spend: 52400,
    spendFormatted: "$52,400",
    verifiedRevenue: 167680,
    verifiedRevenueFormatted: "$167,680",
    discrepancyPct: 1.2,
    verificationStatus: "verified",
    revenueSource: "Stripe",
    lastSyncLabel: "2 min ago",
    attributionWeight: 0.34,
    attributionMethod: "bayesian",
    roas: {
      estimate: 3.2,
      lower: 2.8,
      upper: 3.6,
      bucket: "narrow",
      formattedEstimate: "3.20",
      formattedLower: "2.80",
      formattedUpper: "3.60",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.94,
    divergenceFlag: false,
    cpl: 29,
    cplFormatted: "$29.00",
    conversions: 1808,
    trend: { direction: "up", value: "↑ 7%", period: "vs last 30 days" },
  },
  {
    channelId: "meta",
    channelName: "Meta",
    platform: "meta",
    colorIndex: 2,
    spend: 38150,
    spendFormatted: "$38,150",
    verifiedRevenue: 95375,
    verifiedRevenueFormatted: "$95,375",
    discrepancyPct: -12.6,
    verificationStatus: "partial",
    revenueSource: "Stripe",
    lastSyncLabel: "14 min ago",
    verificationPartialPct: 68,
    attributionWeight: 0.28,
    attributionMethod: "bayesian",
    roas: {
      estimate: 2.5,
      lower: 1.8,
      upper: 3.4,
      bucket: "medium",
      formattedEstimate: "2.50",
      formattedLower: "1.80",
      formattedUpper: "3.40",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.78,
    divergenceFlag: false,
    cpl: 45,
    cplFormatted: "$45.00",
    conversions: 848,
    trend: { direction: "down", value: "↓ 3%", period: "vs last 30 days" },
  },
  {
    channelId: "tiktok",
    channelName: "TikTok",
    platform: "tiktok",
    colorIndex: 3,
    spend: 21900,
    spendFormatted: "$21,900",
    verifiedRevenue: 26280,
    verifiedRevenueFormatted: "$26,280",
    discrepancyPct: 4.5,
    verificationStatus: "verified",
    revenueSource: "Stripe",
    lastSyncLabel: "6 min ago",
    attributionWeight: 0.15,
    attributionMethod: "bayesian",
    roas: {
      estimate: 1.2,
      lower: 0.8,
      upper: 1.6,
      bucket: "wide",
      formattedEstimate: "1.20",
      formattedLower: "0.80",
      formattedUpper: "1.60",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.61,
    divergenceFlag: true,
    cpl: 65,
    cplFormatted: "$65.00",
    conversions: 336,
    trend: { direction: "up", value: "↑ 15%", period: "vs last 30 days" },
  },
  {
    channelId: "linkedin",
    channelName: "LinkedIn",
    platform: "linkedin",
    colorIndex: 4,
    spend: 18600,
    spendFormatted: "$18,600",
    verifiedRevenue: 55800,
    verifiedRevenueFormatted: "$55,800",
    discrepancyPct: 2.1,
    verificationStatus: "verified",
    revenueSource: "Stripe",
    lastSyncLabel: "4 min ago",
    attributionWeight: 0.23,
    attributionMethod: "bayesian",
    roas: {
      estimate: 3.0,
      lower: 2.2,
      upper: 3.9,
      bucket: "medium",
      formattedEstimate: "3.00",
      formattedLower: "2.20",
      formattedUpper: "3.90",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.82,
    divergenceFlag: false,
    cpl: 38,
    cplFormatted: "$38.00",
    conversions: 490,
    trend: { direction: "neutral", value: "— 0%", period: "vs last 30 days" },
  },
  {
    channelId: "pinterest",
    channelName: "Pinterest",
    platform: "pinterest",
    colorIndex: 5,
    spend: 14200,
    spendFormatted: "$14,200",
    verifiedRevenue: 38500,
    verifiedRevenueFormatted: "$38,500",
    discrepancyPct: -3.8,
    verificationStatus: "partial",
    revenueSource: "Stripe",
    lastSyncLabel: "22 min ago",
    verificationPartialPct: 72,
    attributionWeight: 0.12,
    attributionMethod: "bayesian",
    roas: {
      estimate: 1.9,
      lower: 1.2,
      upper: 2.8,
      bucket: "medium",
      formattedEstimate: "1.90",
      formattedLower: "1.20",
      formattedUpper: "2.80",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.68,
    divergenceFlag: false,
    cpl: 52,
    cplFormatted: "$52.00",
    conversions: 274,
    trend: { direction: "down", value: "↓ 2%", period: "vs last 30 days" },
  },
  {
    channelId: "snapchat",
    channelName: "Snapchat",
    platform: "snapchat",
    colorIndex: 6,
    spend: 9600,
    spendFormatted: "$9,600",
    verifiedRevenue: 17250,
    verifiedRevenueFormatted: "$17,250",
    discrepancyPct: 5.4,
    verificationStatus: "unverified",
    revenueSource: "Platform",
    lastSyncLabel: "3 hr ago",
    attributionWeight: 0.08,
    attributionMethod: "bayesian",
    roas: {
      estimate: 1.4,
      lower: 0.9,
      upper: 2.1,
      bucket: "wide",
      formattedEstimate: "1.40",
      formattedLower: "0.90",
      formattedUpper: "2.10",
      rangeLabel: "80% HDI",
    },
    agreementScore: 0.52,
    divergenceFlag: true,
    cpl: 72,
    cplFormatted: "$72.00",
    conversions: 133,
    trend: { direction: "up", value: "↑ 4%", period: "vs last 30 days" },
  },
];

export const AVAILABLE_CHANNELS: AvailableChannel[] = [
  // Core channels (initially selected) — can be re-added after removal
  { channelId: "google_ads", channelName: "Google Ads", platform: "google_ads", hasData: true },
  { channelId: "meta", channelName: "Meta", platform: "meta", hasData: true },
  { channelId: "tiktok", channelName: "TikTok", platform: "tiktok", hasData: true },
  { channelId: "linkedin", channelName: "LinkedIn", platform: "linkedin", hasData: true },
  // Additional channels
  { channelId: "pinterest", channelName: "Pinterest", platform: "pinterest", hasData: true },
  { channelId: "snapchat", channelName: "Snapchat", platform: "snapchat", hasData: true },
];

export const NEXT_COLOR_INDICES = [5, 6];
