export const FIRST_TRUST_ENVELOPE_COPY = {
  step5: {
    heading: 'Generate first TrustEnvelope',
    body: 'Your first envelope will show verified revenue, attribution model, confidence state, policy authority, and audit reference.',
    generateLabel: 'Generate first TrustEnvelope',
    generating: 'Generating first TrustEnvelope…',
    queued: 'TrustEnvelope generation queued. Waiting for deterministic verification.',
    progressOver2s: 'Still generating your first TrustEnvelope. Deterministic verification remains active.',
    retryLabel: 'Retry generation',
    success: 'First TrustEnvelope generated.',
    alreadyExists: 'A first TrustEnvelope already exists for this workspace.',
    replayRejected: 'Generation replay rejected. Use the existing TrustEnvelope state.',
    permissionDenied: 'You do not have permission to generate a TrustEnvelope.',
    rateLimited: 'Generation rate limited. Try again shortly.',
    networkError: 'Trust API read failed. No financial truth was changed.',
    unknownError: 'TrustEnvelope generation failed. No financial truth was changed.',
    schemaInvalid: 'TrustEnvelope response was incomplete. Generation cannot be shown as complete.',
    payloadOversized:
      'TrustEnvelope summary exceeded the transport size budget. Full payload rendering is blocked.',
    payloadRejected:
      'TrustEnvelope response included forbidden full-payload fields. Summary hydration rejected.',
    nakedScalarConfidence:
      'Confidence arrived without probabilistic interval shape. Summary hydration rejected.',
    auditUnavailable: 'Audit substrate unavailable. Generation success cannot be confirmed.',
    lockedWorkspace: 'Complete workspace creation before generating a TrustEnvelope.',
    lockedCommerce: 'Connect commerce truth before generating a TrustEnvelope.',
    lockedPrivacy: 'Confirm the privacy boundary before generating a TrustEnvelope.',
    lockedPolicy: 'Policy authority is unavailable. Generation is blocked.',
    lockedAudit: 'Operational audit substrate is unavailable. Generation is blocked.',
    waitingEvent:
      'No verified commerce event is available yet. Skeldir will not fabricate verified revenue. Return after commerce events are verified.',
    waitingEventAction: 'Manage integrations',
    generateDisabledReason: 'Complete prerequisites before generating.',
    continueToStep6: 'Continue to invite teammates',
    viewSummary: 'View generation summary',
    attributionNote: 'Attribution model output — not deterministic financial truth.',
    claimTruthWarning: 'Platform claims are not verified revenue. Commerce evidence is the authority source.',
  },
  step6: {
    heading: 'Invite teammates',
    body: 'Humans supervise tenant trust surfaces. Team invitations do not create or alter verified revenue truth.',
    humanPathTitle: 'Invite humans',
    humanPathBody: 'Use team settings to invite supervisors with role constraints.',
    humanPathLink: 'Open team settings',
    permissionDenied: 'Your role cannot invite teammates. Contact a workspace owner or admin.',
    completeLabel: 'Complete activation',
    lockedBeforeEnvelope: 'Generate the first TrustEnvelope before inviting teammates.',
    truthBoundary:
      'Inviting teammates does not create or alter verified revenue truth.',
  },
  summary: {
    envelopeId: 'TrustEnvelope ID',
    subjectRef: 'Verified commerce event',
    verifiedRevenue: 'Verified revenue',
    attributionModel: 'Attribution model',
    confidence: 'Confidence state',
    policyAuthority: 'Policy authority',
    auditReference: 'Audit reference',
    generatedAt: 'Generated at',
    hashMetadata: 'Hash metadata',
    auditLinkLabel: 'View audit event',
    missingAuditReference: 'Audit reference missing. Generation cannot be shown as complete.',
  },
} as const;
