openapi: 3.1.0
info:
  title: Skeldir PayPal Webhooks
  version: 2.0.0
  description: |
    PayPal webhook schemas for payment capture events.
    Used for payment verification and revenue reconciliation.
  contact:
    name: Skeldir Engineering
    email: engineering@skeldir.com
    url: https://skeldir.com

servers:
  - url: http://localhost:4018
    description: Prism Mock Server (PayPal Webhooks)

tags:
  - name: PayPal Webhooks
    description: PayPal webhook endpoints for payment events

security:
  - tenantKeyAuth: []

paths:
  /api/webhooks/paypal/sale_completed:
    post:
      summary: PayPal sale completed webhook
      description: Triggered when a PayPal payment sale is completed
      operationId: paypalSaleCompleted
      tags:
        - PayPal Webhooks
      parameters:
        - name: PAYPAL-TRANSMISSION-ID
          in: header
          required: false
          schema:
            type: string
          description: PayPal transmission ID
        - name: PAYPAL-TRANSMISSION-SIG
          in: header
          required: false
          schema:
            type: string
          description: PayPal transmission signature
        - name: PAYPAL-CERT-URL
          in: header
          required: false
          schema:
            type: string
            format: uri
          description: URL to PayPal certificate for verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayPalEvent'
            example:
              id: WH-1234567890
              event_type: PAYMENT.SALE.COMPLETED
              create_time: '2025-11-26T14:30:00Z'
              resource:
                id: "1234567890"
                state: completed
                amount:
                  total: "199.99"
                  currency: USD
                custom_id: sess_abc123
      responses:
        '200':
          $ref: '#/components/responses/WebhookAccepted'
        '400':
          $ref: '../_common/base.yaml#/components/responses/ValidationError'
        '500':
          $ref: '../_common/base.yaml#/components/responses/ServerError'

  /api/webhooks/paypal/payment/capture/completed:
    post:
      summary: PayPal payment capture completed webhook
      description: Triggered when a PayPal payment capture is completed
      operationId: paypalPaymentCaptureCompleted
      tags:
        - PayPal Webhooks
      parameters:
        - name: PAYPAL-TRANSMISSION-ID
          in: header
          required: false
          schema:
            type: string
        - name: PAYPAL-TRANSMISSION-SIG
          in: header
          required: false
          schema:
            type: string
        - name: PAYPAL-CERT-URL
          in: header
          required: false
          schema:
            type: string
            format: uri
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayPalEvent'
            example:
              id: WH-9876543210
              event_type: PAYMENT.CAPTURE.COMPLETED
              create_time: '2025-11-26T15:00:00Z'
              resource:
                id: "CAP-1234567890"
                state: completed
                amount:
                  total: "249.99"
                  currency: USD
                custom_id: sess_xyz789
      responses:
        '200':
          $ref: '#/components/responses/WebhookAccepted'

  /api/webhooks/paypal/payment/sale/refunded:
    post:
      summary: PayPal sale refunded webhook
      description: Triggered when a PayPal payment is refunded
      operationId: paypalSaleRefunded
      tags:
        - PayPal Webhooks
      parameters:
        - name: PAYPAL-TRANSMISSION-ID
          in: header
          required: false
          schema:
            type: string
        - name: PAYPAL-TRANSMISSION-SIG
          in: header
          required: false
          schema:
            type: string
        - name: PAYPAL-CERT-URL
          in: header
          required: false
          schema:
            type: string
            format: uri
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayPalEvent'
      responses:
        '200':
          $ref: '#/components/responses/WebhookAccepted'

components:
  securitySchemes:
    tenantKeyAuth:
      type: apiKey
      in: header
      name: X-Skeldir-Tenant-Key
      description: Tenant API key required for webhook ingestion
  responses:
    WebhookAccepted:
      description: Webhook processed successfully
      content:
        application/json:
          schema:
            $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'
          example:
            success: true
            correlation_id: 00000000-0000-0000-0000-000000000000
            message: Webhook received

  schemas:
    PayPalEvent:
      type: object
      required:
        - id
        - event_type
        - resource
      properties:
        id:
          type: string
          description: Unique webhook event ID
          example: WH-1234567890
        event_type:
          type: string
          enum:
            - PAYMENT.SALE.COMPLETED
            - PAYMENT.CAPTURE.COMPLETED
            - PAYMENT.SALE.REFUNDED
            - PAYMENT.CAPTURE.REFUNDED
          description: Type of PayPal event
        create_time:
          type: string
          format: date-time
          description: Event creation timestamp
        resource_type:
          type: string
          description: Type of resource in the event
        summary:
          type: string
          description: Human-readable event summary
        resource:
          $ref: '#/components/schemas/PayPalResource'

    PayPalResource:
      type: object
      required:
        - id
        - amount
      properties:
        id:
          type: string
          description: Resource ID
        state:
          type: string
          enum: [completed, pending, refunded, partially_refunded]
          description: Current state of the resource
        amount:
          type: object
          required:
            - total
            - currency
          properties:
            total:
              type: string
              description: Total amount as string
              example: "199.99"
            currency:
              type: string
              pattern: '^[A-Z]{3}$'
              description: Currency code
              example: USD
        custom_id:
          type: string
          description: Custom ID containing attribution data (e.g., session ID)
          example: sess_abc123
        invoice_id:
          type: string
          description: Invoice ID if applicable
        parent_payment:
          type: string
          description: Parent payment ID
        create_time:
          type: string
          format: date-time
        update_time:
          type: string
          format: date-time
        links:
          type: array
          items:
            type: object
            properties:
              href:
                type: string
                format: uri
              rel:
                type: string
              method:
                type: string
