openapi: 3.1.0
info:
  title: Skeldir Shopify Webhooks
  version: 2.0.0
  description: |
    Shopify webhook schemas for order and checkout events.
    These webhooks are received by the backend for revenue verification.

servers:
  - url: http://localhost:4015
    description: Prism Mock Server (Shopify Webhooks)

paths:
  /webhooks/shopify/orders/create:
    post:
      summary: Shopify order created webhook
      description: Triggered when a new order is created in Shopify
      operationId: shopifyOrderCreated
      tags:
        - Shopify Webhooks
      parameters:
        - name: X-Shopify-Hmac-SHA256
          in: header
          required: true
          schema:
            type: string
          description: HMAC signature for webhook verification
        - name: X-Shopify-Shop-Domain
          in: header
          required: true
          schema:
            type: string
          description: Shop domain that triggered the webhook
        - name: X-Shopify-Topic
          in: header
          required: true
          schema:
            type: string
            enum: [orders/create]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopifyOrder'
            example:
              id: 820982911946154508
              order_number: 1001
              total_price: "199.99"
              currency: USD
              created_at: '2025-11-26T14:30:00Z'
              note_attributes:
                - name: skeldir_session_id
                  value: sess_abc123
                - name: utm_source
                  value: facebook
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'
        '401':
          description: Invalid HMAC signature
        '500':
          $ref: '../_common/base.yaml#/components/responses/ServerError'

  /webhooks/shopify/checkouts/update:
    post:
      summary: Shopify checkout updated webhook
      description: Triggered when a checkout is updated in Shopify
      operationId: shopifyCheckoutUpdated
      tags:
        - Shopify Webhooks
      parameters:
        - name: X-Shopify-Hmac-SHA256
          in: header
          required: true
          schema:
            type: string
        - name: X-Shopify-Shop-Domain
          in: header
          required: true
          schema:
            type: string
        - name: X-Shopify-Topic
          in: header
          required: true
          schema:
            type: string
            enum: [checkouts/update]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopifyCheckout'
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'

components:
  schemas:
    ShopifyOrder:
      type: object
      required:
        - id
        - order_number
        - total_price
        - created_at
      properties:
        id:
          type: integer
          format: int64
          description: Shopify order ID
        order_number:
          type: integer
          description: Human-readable order number
        total_price:
          type: string
          description: Total order price as string
        subtotal_price:
          type: string
          description: Subtotal before taxes and shipping
        total_tax:
          type: string
          description: Total tax amount
        currency:
          type: string
          description: Currency code
          example: USD
        created_at:
          type: string
          format: date-time
        confirmed:
          type: boolean
          description: Whether the order is confirmed
        financial_status:
          type: string
          enum: [pending, paid, refunded, voided]
        note_attributes:
          type: array
          description: Custom attributes including attribution data
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
        customer:
          type: object
          properties:
            id:
              type: integer
              format: int64
            email:
              type: string
              format: email
        line_items:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
              title:
                type: string
              quantity:
                type: integer
              price:
                type: string

    ShopifyCheckout:
      type: object
      required:
        - token
        - total_price
      properties:
        token:
          type: string
          description: Checkout token
        total_price:
          type: string
          description: Total checkout price
        subtotal_price:
          type: string
        currency:
          type: string
        abandoned_checkout_url:
          type: string
          format: uri
        note_attributes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
