openapi: 3.1.0
info:
  title: Skeldir Stripe Webhooks
  version: 2.0.0
  description: |
    Stripe webhook schemas for payment events.
    Used for payment verification and revenue reconciliation.

servers:
  - url: http://localhost:4017
    description: Prism Mock Server (Stripe Webhooks)

paths:
  /webhooks/stripe/charge/succeeded:
    post:
      summary: Stripe charge succeeded webhook
      description: Triggered when a charge is successfully completed
      operationId: stripeChargeSucceeded
      tags:
        - Stripe Webhooks
      parameters:
        - name: Stripe-Signature
          in: header
          required: true
          schema:
            type: string
          description: Stripe webhook signature for verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeEvent'
            example:
              id: evt_1234567890
              type: charge.succeeded
              created: 1732631400
              data:
                object:
                  id: ch_1234567890
                  amount: 19999
                  currency: usd
                  status: succeeded
                  metadata:
                    skeldir_session_id: sess_abc123
                    order_id: ord_12345
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'
        '400':
          description: Invalid webhook signature
        '500':
          $ref: '../_common/base.yaml#/components/responses/ServerError'

  /webhooks/stripe/payment_intent/succeeded:
    post:
      summary: Stripe payment intent succeeded webhook
      description: Triggered when a payment intent is successfully completed
      operationId: stripePaymentIntentSucceeded
      tags:
        - Stripe Webhooks
      parameters:
        - name: Stripe-Signature
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeEvent'
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'

  /webhooks/stripe/charge/refunded:
    post:
      summary: Stripe charge refunded webhook
      description: Triggered when a charge is refunded
      operationId: stripeChargeRefunded
      tags:
        - Stripe Webhooks
      parameters:
        - name: Stripe-Signature
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeEvent'
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                $ref: '../_common/base.yaml#/components/schemas/SuccessResponse'

components:
  schemas:
    StripeEvent:
      type: object
      required:
        - id
        - type
        - data
        - created
      properties:
        id:
          type: string
          description: Unique event identifier
          example: evt_1234567890
        type:
          type: string
          enum:
            - charge.succeeded
            - charge.refunded
            - payment_intent.succeeded
            - payment_intent.payment_failed
          description: Event type
        created:
          type: integer
          description: Unix timestamp of event creation
        livemode:
          type: boolean
          description: Whether this is a live mode event
        data:
          type: object
          required:
            - object
          properties:
            object:
              $ref: '#/components/schemas/StripeCharge'

    StripeCharge:
      type: object
      required:
        - id
        - amount
        - currency
        - status
      properties:
        id:
          type: string
          description: Charge ID
          example: ch_1234567890
        amount:
          type: integer
          description: Amount in cents
          example: 19999
        amount_refunded:
          type: integer
          description: Amount refunded in cents
          example: 0
        currency:
          type: string
          description: Three-letter currency code
          example: usd
        status:
          type: string
          enum: [succeeded, pending, failed]
        paid:
          type: boolean
          description: Whether the charge was paid
        refunded:
          type: boolean
          description: Whether the charge was fully refunded
        metadata:
          type: object
          description: Custom metadata including attribution data
          additionalProperties:
            type: string
          example:
            skeldir_session_id: sess_abc123
            order_id: ord_12345
        receipt_email:
          type: string
          format: email
        billing_details:
          type: object
          properties:
            email:
              type: string
              format: email
            name:
              type: string
